using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Diagnostics;
using System.Drawing;
using System.IO;
using System.Runtime.InteropServices;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using System.Windows.Forms;
using Be.Windows.Forms;

namespace GUI
{
	public partial class frmMain : Form
	{
		private List<string> _tracedColumns = new List<string> { "cycle", "hpos", "vpos", "vbl_flag", "spr0_hit", "spr_overflow", "vramaddr_t", "vramaddr_v", "io_db", "io_ab", "io_rw", "io_ce", "rd", "wr", "ab", "ale", "db" };
		private bool _autoRun = false;
		private object _runLock = new object();
		private int _stepsToRun = 0;
		private bool _needColumnUpdate = true;
		private EmulationState state = new EmulationState();
		List<string> _resetStates = new List<string>() {
			/*resetStatePostrenderOdd*/ "xvgllhlllllllhxxxhhlllllxllllllhxxxhhlxlllllllllllhhhhlllllxhhhlllllllllhllllhxlhxxhxlllhxxxxhllxlxllxxxxlhlxxxlxllhlxhlhlxhxhlxlxxxxxxlxxxxxxxxxxxxxhhxhhxhllxxxxxlxxxxhxlhlxxxxxxhlxxxxxxxxxlhxhlllhhlxxxhhhxxxllxhxlxxxhllllhhlhhlllhxxllxlxhhhxlhlxhhxhxxhhhxxxlllxxxxxxxxxxhhlxxlllhllhxlxxlxxhxxlxxhxxlhxhhxlhlhllxhxxlllllllllllllxxlxlhllxxxxhxxlxlxxxhxxxxhhlxlxxlxhlxhhxxxxhxxlllxlhllxxxhxlllxxxxlllxxxxxxlxxxxxxxxhhxxxlxhhlxxlllhllhlllhllhllhllllhxlhlhlllxxlhlllhxxxlxxxxxllhhhlxxhllhhxlhlhhxxxlhxlhhxxxllllllhlxxxhhxlxxxlllxhhxxlxxlxxhllxxxhhlhhlhxxxllxxxxllhxxxxllxxxxxhlllxxxxxxxllxxxhlxxxxxxxlllxxlllxxxlxxlxllxllhlhlhlhllhhlhllxxxxlllxxxllxxxxxxlxxxhhxxxxlxlhlhxxhxhxxxxxxxlxhxxxxhlhhllhxlhxxxxxxxxxxhxhxxlxxhxxlllxxxxlxxxlxhhhxxlxxxxxxxlxlhxxxxllxxxxxlxxxxxxlxxxxxlhhhxxxxxxhxxxxxhxlhxxxxxxxxxxxllxxxlxhlllxlxlllxlxlllxhlllhhlllllllllllllllllllhlllhlxxlxxlllhlxllllllhhhhhhhhhxxxxxxxxlllllhhxxxxllhllllllllxllllhlxhlxxxxxxhxhxhxhxllhlhlxlllxllhlhllxlxxxhxxxxxxlxhxhhxxllllhhhhxlxlxllxhlxlxlxxxhhllxxhlxlxxxlhhxxxxxxxxxxlxxxhhxxlxllllxxhxxxxlxxxhllxxhhlxxxxxlxxxxlllxxxxxlxhxlxxlhxxxxllxlxxlxhllxhxxhxlxlxlhlhlxhxxxlxxllllhlxlhhxxlxhxllllxxllhxxlxlhxllxhxllxxlllhxlxhhhxxhxlxxhxhhxxxhxlxhlxxxxxlhxlxxxhhlxlxxxllhxxlxxxllxxxxxxxxllxxhxxhxhxhxxhhxhxhxxxlhxxhxlxlllxhlxxxhlhlxlllhhhxxhxhxhxhxhxhxxxxhxhlxxxxlhxxxhxxxxllhxxxxllhlxlxhxlhlxhlllxxxxlhhxxxhlhhxlxhxxxxxxxlllhhhhhhlxxxxlllhxlxxlxllxxllxxlxxxlhhlhhhlhhhhhhllhhhlhlhlhhlhlhlhhlhlhlhlhlhlhhhlhlhlhlhhxllhxxxxxxxxxlxxhxxxxxlxxxlhlxxhlxxxxlhlxhxxhlxxlxxlllxxhxllxlxllxhlxlxhlxhxllxhlhxxxlxxxhllxxxlhllxxxhllxxxhlhxlllllhlxlhxxlxxhlhxxhhxxlxlhxhhlllxxxxllxxxhxxxxxxxxxhxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxhxxxxxlxxxxlhxxlhxhhxxxxlxxxxxlxxxlxxxlxxxlxxhxxlxlxxxlxlhllhxxxlxlhxxxxlxxxhlxhxxxxxhlxxxxxxhxxxxxxhxxxxxxxxxxxlxxxlllllxlhlxxxlllllxlhxxlhllxhxxxxxxlxxxxlxhllllhllllhllhlllhhlllxllxhlxxllxxlhxlllxhxxhhxxhxxlxhhhhhhhhhhhhhhhhhxxxxhhhhhhhhhhhhhhhhxhxxxxxxxhhhhhhhhhhhhhhhhhxxxxxlhhhhhhhhhhhhhhxhhlxlxxlxxhxxhhhhhhhhhhhhhhhhhxxhxxlhxhxhhhhhhhhhhhhhxhhhhhxlhxhxhlxxxhhhhhhhhhhhhhhhhlhxhxhllxxxxxxxxxxxxxxlllxxxxxlxhxlxhxxxxxxxxhllllhlxlhlhlhlxhlhxlhlhlhlhlhllhllhhxhlllhxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxllllllllxxxxxxxxhhhhhhhlxxxxxxxxxllllllllxxxxxlxxlxxlxxlxxhxllxxlxxxxxxxxxxxxxxxxxxhhhhhxxxxhhhhhhhlllxxlllllxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxllxxxllxlxxlxlhhxxxxlllllllllllllllxhlxxxxxxxxxlxhllllllllllxllxlxxlllxllllllllxxllllllllxhhhhhhhhllllllllhxhhhhhhhhhxllllllllhhhhhhhhxhhhhhhhhxhhhhhhhhxhhhhhhhhhxxxxxxxxxxllllllllxxllllllllxxlxxxxxxxxxllllllllllllllllllllxxxxxxxxxlxllllllllxxxxxxxxxxxxllllllllxllllllllxllllllllxxhxlxllxxxxxxxhlxxlhllllllllxlllxlllllxxhhxxxllxxxxxxxxxhllllllllllxhxllllllllllllxxxxxxxxxllllllllxxllllllllxxxxhxxxxxxxxlllllllllhxhxhxhhhhxxxxxxxxxxxxxxxxhxxxxxxxxxxxxxxxxxllllllllllxlxxxlxxxxxxxxhhhllllllllllxxxxxxllllllllllllxlllxxlxllllllxxxxxxhhhhhhllxxllllllllllllllllxxxxxxxxxxxxllllllhllhhhhhhlllllhllhhhhlxhlxlhxlhxlhhlxlllhhhlllxhxxlhllxlhlxllxxxxxxxxxllxxhllllllllllllllllllllllllllllllllxhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhlllhhhllllllllllllllllllllllllllllllllllhhlhhlllllhlhlllllllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhxxxxllllllllllllllllllllllllllllllllxxxxxxhllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhlhhhhhllllllllllllllllllllllllllllllllxllhhlxhhllhxhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhlllllllllllllllllllllllllllllllllxxlxxxxxxxxxlhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhxhlhllllllhllllllllllllllllllllllllllllllllllhhlllhlhlhhhhhhxxxlllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllxxhlhllllllxhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhxxxxxxxxllllllllllllllllllllllllllllllllxllhllhhhxlxlhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhlllllllllllllllllllllllllllllllllxxxxxhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhlxlxllllllllllllllllllllllllllllllllllxxxllllhlxlhxhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhlhllllllllllllllllllllllllllllllllxxxhllhhhhhxhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhxxxxxxxlllllllllllllllllllllllllllllllllllhhhhlhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhxlllllllllllllllllllllllllllllllllhllxxxxxxhhxxhlhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllhhllhlllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhxlllllllllllllllllllllllllllllllllllxlhhhxhlxxhhlhhhlllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllhllhllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhxxxxxxlxlllllllllllllllllllllllllllllllllxxxxxllxxlhxxxllhllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhxlllllllllllllllllllllllllllllllllxlxxlxllllhllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhlllllllllllllllllllllllllllllllllllllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhlhhxlllllllllllllllllllllllllllllllllxllhxllllhlhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhxllllllllllllllllllllllllllllllllllllxhhllhllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllxxlxxlhlhllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhlllllllllllllllllllllllllllllllllxxxxxxxxxxxxxxlhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhxlllllllllllllllllllllllllllllllllxxhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhlxxxxxxxxxxxxxxxxxllllllllllllllllllllllllllllllllllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhlllllllllllllllllllllllllllllllllxlxxxxxhlhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllxxxxhllhhhhhlhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllhhlhlhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllhhhhlllxhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllxlhhhhhxxxlxhxhlhhhllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllhlllllllllllllllllllllllllllllllllllhxlhhlhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllxlxxxxhllllxlxxxxxxxxxxxxlhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllllxlxllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhxxxxlllllllllllllllllllllllllllllllllhlhlllllllllllllhlllllllllxlllllhlhllllllllllllllllllllllllllllllllhhhhllllhlhhhhlllhhhllxllhhlhhhxhlhhhhhhhlxlhlhlxhhxlhhllhlhxhhhhhllhxllxxxlhhlhlhhhlhhhhlhhhlhllhhlllllhlxlhlxhlhhhllhxhllxlxhllllhhhxhllxhlxlhlhxllxxhxxxhxhxhhlhxllxxlxllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhxlllllllllllllllllllllllllllllllllxlhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhlllllllllllhhllllllllllllllllllllllllllllllllhxhhxhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllxllxxhhhhhhhhhhhhhhlxxhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllxllllllxllllllllllllllllllllxhlxhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllhlhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhlxllllllllllllllllllllllllllllllllxxxxxxxxxxxxxxllhlxxhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhxhhllllllllllllllllllllllllllllllllhxhxhxlxhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllhlllllxllllllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllxxxxxxhhhllllllllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllxllllllllllllllllllllllllllllllllhllllllllhhlllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhlxlllllllllllllllllllllllllllllllllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhlllllllllllllllllllllllllllllllllllllllhxxxxxxxlxxxxxxxxxxxxlllllllllllllxhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllllllllxlhhhxhhxlhhxxhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllxlhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllxxxxxxhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhxxxxxxllllllllllllllllllllllllllllllllxxxlhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhlllllllllllllllllllllllllllllllllxhhlhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllllllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllllhxxxxxhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhlllllllllllllllllllllllllllllllllhxllllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhxlllllllllllllllllllllllllllllllllllllxlllllllllllllllllllllllllhhhhhhhhhhhhhhhhhhhhhhhhlhhhhlhhhhhxlhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllxlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllllllhhhlhhhhhllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhlllllllllllllllllllllllllllllllllllllllllllllllllllllllllllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhlhllllllllllllllllllllllllllllllllllllhhhhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllxlllxlhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhlllllllllllllllllllllllllllllllllllllllllllllllllllllllllhhhhhhhhhhhhhhhhhhhhhhhhxlhhhhxlxhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhlllllllllllllllllllllllllllllllllhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhlllllllllllllllllllllllllllllllllxlxxxxhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhlllllllllllllllllllllllllhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllxxxxlxxxlhlxxxxxxxhlxhhhhhhxxxxxllllllxhlllhhhhhhhhhhhhhhlhhlhlhlhlhlhlhlhlxxxxxxxlllhlhhllllhlhlhlhlhllhhhhhlhllxxxxxxxxllllllllxxxxxxxxllllllllhhhhhhhhhhhhhhhhllllllllllllllllllhlhhhhhhhhlhhlllllxxxxxxxxxxxllllllllxxxxxxxxhhllhhllhhllhhllhhhhhhhhhhlllllllllllllllllhxhhxxxxxxxxllllllllxxxxxxxxhhllhhllhhllhhllhhhhhhhhhlllllllllllllllllhxhllllllllhhhhxxxxxxxxllllllllxxxxxxxxhllhhllhhllhhllhhhhhhhhhhhlllllllllhhhhhhhhlllllhllllllllllhxxxhhxxxxxxxxlllllllllxxxxxxxxxlhllhhllhhllhhllhhhhhhhhhllllllllllllllllllllllllllllllhhllxhhhhhhhhhhhhhxxxxxxxxllllllllhxxxxxxxxhllhhllhhllhhllhhhhhhhhhlllllllllllllllllllllxlllllllllhxxllxxxxxxxxxhllllllllhhhhhhhhhhhhhxxxxxxxxhllhhllhhllhhllhhhhhhhhhlllllllllllllllllhxhxxxxxxxxxllllllllxxxxxxxxxhllhhllhhllhhllhhhhhhhhhhllllllllhllllllllllhxhlxxxxxxxxxlhhhhhhhhhlxhhhhhhhhxxxxxxxxxxxxllxxxxllllllhhhhhhhhxxxxxxxxxxxxxxxhhhhhhhhhllllllllhhhhhhhhhhhhhllhhhhllllllxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxhhxxxxxxxxxxxxxxxxxxxxxxxxxhhhhhhhhhhhhhhllllhllllxhhlllllllllllllllhhxhxxxxhhllllllllllllllhllllxhxlxxhllllllllxlllllllllllllxxxxxxxxxhxhhhhhhhhxxxxxxxxlhhhhhhhhhhhhhhhhhhxxxxxxxxllllxxxxxxxxxhxxxxxxxxxxxxxxxxxxxhhhhhhhhlllxxxxxxxxlhhhhhhhhxhhhhhhhhhxxxhhhhhhhhllllllllxllllllllllllllllllhhhhhhhhlllxxxxxxxxlhhhhhhhhxhhhhhhhhhxhhhhhhhhllllllllhhhhhhhhhhhhhhhhhhhhhhhhxxxxxxxxhhhhhhhhxllllllllhhhhhhhhhhhhhhhhllllllllhhllllllllhhhlxxxxxxxxxhhhhhhhhhxhlxxxhhhhhhhhhllhhhhhhhhlllllllllllhxhhhllllllllhhhhhhllllxxxxxxxxlllhhhhhhhhllllllhhhhhhhhhlllxhhhhhhhhhxhhhhhhhhlllllllllxhhllllllllhhhhhhhhhhhhlxhllhhhhhhhhllllllxlxhxllllxxxxxxxxlhhhhhhhhxxxxxhhhhhhhhhxhhhhhhhhlllllllllllllllllllllllllllllllllllllllllllxxxxxxxxlhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhxhhhhhhhhhxxxhhhhhhhhllllllllxxllllllllllllllllllllllllllllllllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhxxxxxxxxhhhhhhhhllllllllllllllllhhhhhhhhlhhllhhhhhhhhhhhxlxxllhlllhhllhxllhlhxxhlhlhhhhhllhhlhhhllxhhhhhhhhhhxxxxxllllllhllhhhhhxlllhllhlhhllllllllllllxlllllllllllhlhllhlllllllhhhhhhlllllllhllllllllllhlllhhhhllllllllllllllllllllllxllhhhhhhhhhhhhhhlhhllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh",
			/*resetStatePrerenderOdd */ "xvgllhlllllllhxxxhhlllllxllllllhxxxhhlxlllllllllllhhhhlllllxhhhlllllllllhllllhxlhxxhxlllhxxxxhllxlxllxxxxlhlxxxlxllhlxhlhlxhxlhxlxxxxxxlxxxxxxxxxxxxxhhxhlxhllxxxxxlxxxxhxlhlxxxxxxhlxxxxxxxxxllxhlllhhlxxxhhhxxxlhxhxlxxxhllllhhlhhlllhxxllxlxhhhxlhlxhhxhxxhhhxxxlllxxxxxxxxxxhhlxxlllhllhxlxxlxxhxxlxxhxxlhxhlxlhlhlhxhxxlllllllllllllxxlxlhllxxxxhxxlxlxxxhxxxxhhlxlxxlxhlxhhxxxxhxxlllxllllxxxhxlllxxxxlllxxxxxxhxxxxxxxxhhxxxlxlhhxxllllllhlllhllhllhllllhxlhlhlllxxlllllhxxxlxxxxxhllhhlxxhhhhhxlhllhxxxllxlhhxxxhlllllhlxxxhhxlxxxlllxllxxlxxlxxhhlxxxlllhhllxxxllxxxxlhhxxxxllxxxxxhhhlxxxxxxxllxxxllxxxxxxxlllxxlllxxxlxxlxllxllhlhlhlhllhllhlhxxxxlllxxxlhxxxxxxlxxxhhxxxxlxlhlhxxhxhxxxxxxxlxhxxxxhlhhllhxlhxxxxxxxxxxhxhxxlxxhxxlllxxxxlxxxlxhhhxxlxxxxxxxlxlhxxxxlhxxxxxlxxxxxxlxxxxxlhhhxxxxxxhxxxxxhxlhxxxxxxxxxxxllxxxlxhhhhxlxlllxlxlllxhlllhllllllllllllllllhllllhhlhlxxlxxlllllxllllhlhhhhhhhhhxxxxxxxxlllllhlxxxxllhllllllllxllllhlxhlxxxxxxhxhxhxhxlhlhllxlllxlhhlhllxlxxxhxxxxxxlxhxhhxxhhhhhlhlxlxlxllxhlxlxlxxxhhllxxhlxlxxxllhxxxxxxxxxxlxxxhhxxlxlhlhxxhxxxxlxxxhhlxxlhlxxxxxlxxxxlllxxxxxlxhxlxxlhxxxxllxlxxlxhlhxhxxhxlxlxlhlhlxhxxxlxxllllhlxlhhxxlxhxllllxxllhxxlxlhxllxhxllxxlllhxlxhhhxxhxlxxhxhhxxxhxlxhlxxxxxlhxlxxxhhlxlxxxllhxxlxxxllxxxxxxxxllxxhxxhxhxhxxhhxhxhxxxlhxxhxlxlllxhlxxxhlhlxllllhhxxhxhxhxhxhxhxxxxhxhlxxxxlhxxxhxxxxllhxxxxllhlxlxhxlhlxhlllxxxxlhlxxxhlhhxlxhxxxxxxxlllhhhhhhlxxxxlllhxlxxlxllxxllxxlxxxlhhlhhhlhhhhhhllhhhlhlhlhhlhlhlhhlhlhlhlhlhlhhhlhlhlhlhhxllhxxxxxxxxxlxxhxxxxxlxxxlhlxxhlxxxxlhlxhxxhlxxlxxlllxxhxllxlxllxhlxlxhlxhxllxhlhxxxlxxxhllxxxlhllxxxhllxxxhlhxlllllhlxlhxxlxxhlhxxhhxxlxlhxhhlllxxxxllxxxhxxxxxxxxxhxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxhxxxxxlxxxxlhxxlhxhhxxxxlxxxxxlxxxlxxxlxxxlxxhxxlxlxxxlxlhllhxxxlxlhxxxxlxxxhlxhxxxxxhlxxxxxxhxxxxxxhxxxxxxxxxxxlxxxlllllxlhlxxxlllllxlhxxlhllxhxxxxxxlxxxxlxhllllhllllhllhlllhhlllxllxhlxxllxxlhxlllxhxxhhxxhxxlxhhhhhhhhhhhhhhhhhxxxxhhhhhhhhhhhhhhhhxhxxxxxxxhhhhhhhhhhhhhhhhhxxxxxlhhhhhhhhhhhhhhxhhlxlxxlxxhxxhhhhhhhhhhhhhhhhhxxhxxlhxhxhhhhhhhhhhhhhxhhhhhxlhxhxhlxxxhhhhhhhhhhhhhhhhlhxhxhllxxxxxxxxxxxxxxlllxxxxxlxhxlxhxxxxxxxxhllllhlxlhlhlhlxhlhxlhlhlhlhlhllhllhhxhlllhxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxllllllllxxxxxxxxhhhhhhhlxxxxxxxxxllllllllxxxxxlxxlxxlxxlxxhxllxxlxxxxxxxxxxxxxxxxxxhhhhhxxxxhhhhhhhlllxxlllllxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxllxxxllxlxxlxlhhxxxxlllllllllllllllxhlxxxxxxxxxlxhllllllllllxllxlxxlllxllllllllxxllllllllxhhhhhhhhllllllllhxhhhhhhhhhxllllllllhhhhhhhhxhhhhhhhhxhhhhhhhhxhhhhhhhhhxxxxxxxxxxllllllllxxllllllllxxlxxxxxxxxxllllllllllllllllllllxxxxxxxxxlxllllllllxxxxxxxxxxxxllllllllxllllllllxllllllllxxhxlxllxxxxxxxhlxxlhllllllllxlllxlllllxxhhxxxllxxxxxxxxxhllllllllllxhxllllllllllllxxxxxxxxxllllllllxxllllllllxxxxhxxxxxxxxlllllllllhxhxhxhhhhxxxxxxxxxxxxxxxxhxxxxxxxxxxxxxxxxxllllllllllxlxxxlxxxxxxxxhhhllllllllllxxxxxxllllllllllllxlllxxlxllllllxxxxxxhhhhhhllxxllllllllllllllllxxxxxxxxxxxxllllllhllhhhhhhlllllhllhhhhlxhlxlhxlhxlhhlxlllhhhlllxhxxlllhxlhlxlhxxxxxxxxxllxxhllllllllllllllllllllllllllllllllxhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhlllhhhllllllllllllllllllllllllllllllllllhhlhhlllllhlhlllllllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhxxxxllllllllllllllllllllllllllllllllxxxxxxhllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllhhhhllllllllllllllllllllllllllllllllxlhhhlxhhlhhxhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhlllllllllllllllllllllllllllllllllxxlxxxxxxxxxlhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhxhlhllllllhllllllllllllllllllllllllllllllllllhhlllhlhlhhhhhhxxxlllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllxxhlhllllllxhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhxxxxxxxxllllllllllllllllllllllllllllllllxlhlhllhhxlxllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllllxxxxxlhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhlxlxllllllllllllllllllllllllllllllllllxxxllllhhxllxhhlhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllllxxxhhlhhhhhxhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhxxxxxxxlllllllllllllllllllllllllllllllllhllhhllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhxllllllllllllllllllllllllllllllllllllxxxxxxhhxxhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllhhllhhlllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhxlllllllllllllllllllllllllllllllllllxllhhxhlxxhhlhhhhllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllhllllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhxxxxxxlxlllllllllllllllllllllllllllllllllxxxxxlhxxlhxxxllhllhlhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhxlllllllllllllllllllllllllllllllllxlxxlxllllhllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhlllllllllllllllllllllllllllllllllllllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhlhhxlllllllllllllllllllllllllllllllllxllhxllllhlhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhxllllllllllllllllllllllllllllllllllllxhhllhllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllxxlxxlhlhllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhlllllllllllllllllllllllllllllllllxxxxxxxxxxxxxxlhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhxlllllllllllllllllllllllllllllllllxxhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhlxxxxxxxxxxxxxxxxxllllllllllllllllllllllllllllllllllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllxlxxxxxhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllxxxxhhhhhlhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllhhhhlllxhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhlllllllllllllllllllllllllllllllllxlhhhhhxxxhxlxlhhhlhhlhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhlllllllllllllllllllllllllllllllllllllllhxlhllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllxlxxxxhllllxlxxxxxxxxxxxxlhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllllxlxllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhxxxxlllllllllllllllllllllllllllllllllhlhlllllllllllllhlllllllllxlllllhlhlllllllllllllllllllllllllllllllllllllhlhhlhhhhlhhhhhllxhhlllhlhxhlhhllllhlxlhlhlxhhxhhhlhllhxhhlhlhlhxllxxxllhlhlhhhlhhlhlhhhlhllhhlhlllhlxhhlxhlhlhlhhxhllxlxhllllhhhxhllxhlxlhlhxhlxxlxxxhxhxhhlhxllxxlxllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhxlllllllllllllllllllllllllllllllllxlhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhlllllllllllhhllllllllllllllllllllllllllllllllhxhhxhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllxllxxhhhhhhhhhhhhhhlxxhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllxllllllxllllllllllllllllllllxhlxhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllhlhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhlxllllllllllllllllllllllllllllllllxxxxxxxxxxxxxxllhlxxlhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhxllllllllllllllllllllllllllllllllllhxhxhxlxhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllhlllllxllllllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllxxxxxxhhhllllllllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllxllllllllllllllllllllllllllllllllhllllllllhhlllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhlxlllllllllllllllllllllllllllllllllhllllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhlhhhhllllllllllllllllllllllllllllllllllhxxxxxxxlxxxxxxxxxxxxllllllhhhhlllxhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllllllllxlhhhxhhxlhhxxhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllxlhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllxxxxxxhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhxxxxxxllllllllllllllllllllllllllllllllxxxlllllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhlllllllllllllllllllllllllllllllllxhhlhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllllllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllllhxxxxxhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhlllllllllllllllllllllllllllllllllhxllllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhxlllllllllllllllllllllllllllllllllllllxlllllllllllllllllllllllllhhhhhhhhhhhhhhhhhhhhhhhhlhhhhlhhhhhxlhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllxlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllllllhhhlhhhhhllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhlllllllllllllllllllllllllllllllllllllllllllllllllllllllllllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhlhllllllllllllllllllllllllllllllllllllhhhhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllxlllxlhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhlllllllllllllllllllllllllllllllllllllllllllllllllllllllllhhhhhhhhhhhhhhhhhhhhhhhhxlhhhhxlxhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhlllllllllllllllllllllllllllllllllhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhlllllllllllllllllllllllllllllllllxlxxxxhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhlllllllllllllllllllllllllhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllxxxxlxxxlhlxxxxxxxhlxhhhhhhxxxxxllllllxhlllhhhhhhhhhhhhlhllhlhlhlhlhlhlhlhlxxxxxxxlhlhhhhllllhlhlhlhlhllhhhhhlhllxxxxxxxxllllllllxxxxxxxxllllllllhhhhhhhhhhhhhhhhllllllllllllllllllhlhhhhhhhhlhhlllllxxxxxxxxxxxllllllllxxxxxxxxhhllhhllhhllhhllhhhhhhhhhhlllllllllllllllllhxhhxxxxxxxxllllllllxxxxxxxxhhllhhllhhllhhllhhhhhhhhhlllllllllllllllllhxhllllllllhhhhxxxxxxxxllllllllxxxxxxxxhllhhllhhllhhllhhhhhhhhhhhlllllllllhhhhhhhhlllllhllllllllllhxxxhhxxxxxxxxlllllllllxxxxxxxxxlhllhhllhhllhhllhhhhhhhhhllllllllllllllllllllllllllllllhhllxhhhhhhhhhhhhhxxxxxxxxllllllllhxxxxxxxxhllhhllhhllhhllhhhhhhhhhlllllllllllllllllllllxlllllllllhxxllxxxxxxxxxhllllllllhhhhhhhhhhhhhxxxxxxxxhllhhllhhllhhllhhhhhhhhhlllllllllllllllllhxhxxxxxxxxxllllllllxxxxxxxxxhllhhllhhllhhllhhhhhhhhhhllllllllhllllllllllhxhlxxxxxxxxxlhhhhhhhhhlxhhhhhhhhxxxxxxxxxxxxllxxxxllllllhhhhhhhhxxxxxxxxxxxxxxxhhhhhhhhhllllllllhhhhhhhhhhhhhllhhhhllllllxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxhhxxxxxxxxxxxxxxxxxxxxxxxxxhhhhhhhhhhhhhhllllhllllxhhlllllllllllllllhhxhxxxxhhllllllllllllllhllllxhxlxxhllllllllxlllllllllllllxxxxxxxxxhxhhhhhhhhxxxxxxxxlhhhhhhhhhhhhhhhhhhxxxxxxxxllllxxxxxxxxxhxxxxxxxxxxxxxxxxxxxhhhhhhhhlllxxxxxxxxlhhhhhhhhxhhhhhhhhhxxxhhhhhhhhllllllllxllllllllllllllllllhhhhhhhhlllxxxxxxxxlhhhhhhhhxhhhhhhhhhxhhhhhhhhllllllllhhhhhhhhhhhhhhhhhhhhhhhhxxxxxxxxhhhhhhhhxllllllllhhhhhhhhhhhhhhhhllllllllhhllllllllhhhlxxxxxxxxxhhhhhhhhhxhlxxxhhhhhhhhhllhhhhhhhhlllllllllllhxhhhllllllllhhhhhhllllxxxxxxxxlllhhhhhhhhllllllhhhhhhhhhlllxhhhhhhhhhxhhhhhhhhlllllllllxhhllllllllhhhhhhhhhhhhlxhllhhhhhhhhllllllxlxhxllllxxxxxxxxlhhhhhhhhxxxxxhhhhhhhhhxhhhhhhhhlllllllllllllllllllllllllllllllllllllllllllxxxxxxxxlhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhxhhhhhhhhhxxxhhhhhhhhllllllllxxllllllllllllllllllllllllllllllllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhxxxxxxxxhhhhhhhhllllllllllllllllhhhhhhhhlhhllhhhhhhhhhhhxlxxllhlllhhllhxllhlhxxhlhlhhhhhllhhlhhhllxhhhhhhhhhhxxxxxllllllhllhhhhhxlllhllhlhhllllllllllllxllllllllllllhhllllllllllllllhhlllllllhllllllllllhlllhhhhllllllllllllllllllllllxllhhhhhhhhhhhhhhlhhllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh",
			/*resetStatePrerenderEven*/ "xvgllhlllllllhxxxhhlllllxllllllhxxxhhlxlllllllllllhhhhlllllxhhhlllllllllhllllhxlhxxhxlllhxxxxhllxlxllxxxxlhlxxxlxllhlxhlhlxhxlhxhxxxxxxlxxxxxxxxxxxxxhhxhlxhllxxxxxlxxxxhxlhlxxxxxxhlxxxxxxxxxllxllhhhllxxxhhhxxxlhxhxlxxxhllllhlhhllhhhxxllxlxhhhxlhlxhhxhxxhhhxxxlllxxxxxxxxxxhhlxxlllhllhxlxxlxxhxxlxxhxxlhxhlxlhlhlhxhxxlllllllllllllxxlxlhllxxxxhxxlxlxxxhxxxxhhlxlxxlxhlxhhxxxxhxxlllxllllxxxhxlllxxxxlllxxxxxxhxxxxxxxxhhxxxlxlhhxxllllllhlllhllhllhllllhxlhlhlllxxlllllhxxxlxxxxxhllhhlxxhhhhhxlhllhxxxllxlhhxxxhlllllhlxxxhhxlxxxlllxllxxlxxlxxhhlxxxlllhhllxxxllxxxxlhhxxxxllxxxxxhhhlxxxxxxxllxxxllxxxxxxxlllxxlllxxxlxxlxllxllhlhlhlhllhllhlhxxxxlllxxxlhxxxxxxlxxxhhxxxxlxlhlhxxhxhxxxxxxxlxhxxxxhlhhllhxlhxxxxxxxxxxhxhxxlxxhxxlllxxxxlxxxlxhhhxxlxxxxxxxlxlhxxxxlhxxxxxlxxxxxxlxxxxxlhhhxxxxxxhxxxxxhxlhxxxxxxxxxxxllxxxlxhhhhxlxlllxlxlllxhlllhllllllllllllllllhllllhhlhlxxlxxlllllxllllhlhhhhhhhhhxxxxxxxxlllllhhxxxxllhllllllllxlllhhlxhlxxxxxxhxhxhxhxlhlhllxlllxlhhlhllxlxxxhxxxxxxlxhxhhxxhhhhhlhlxlxlxllxhlxlxlxxxhhllxxhlxlxxxllhxxxxxxxxxxlxxxhhxxlxlhlhxxhxxxxlxxxhhlxxlhlxxxxxlxxxxlllxxxxxlxhxlxxlhxxxxllxlxxlxhlhxhxxhxlxlxlhlhlxhxxxlxxllllhlxlhhxxlxhxllllxxllhxxlxlhxllxhxllxxlllhxlxhhhxxhxlxxhxhhxxxhxlxhlxxxxxlhxlxxxhhlxlxxxllhxxlxxxllxxxxxxxxllxxhxxhxhxhxxhhxhxhxxxlhxxhxlxlllxhlxxxhlhlxllllhhxxhxhxhxhxhxhxxxxhxhlxxxxlhxxxhxxxxllhxxxxllhlxlxhxlhlxhlllxxxxlhlxxxhlhhxlxhxxxxxxxlllhhhhhhlxxxxlllhxlxxlxllxxllxxlxxxlhhlhhhlhhhhhhllhhhlhlhlhhlhlhlhhlhlhlhlhlhlhhhlhlhlhlhhxllhxxxxxxxxxlxxhxxxxxlxxxlhlxxhlxxxxlhlxhxxhlxxlxxlllxxhxllxlxllxhlxlxhlxhxllxhlhxxxlxxxhllxxxlhllxxxhllxxxhlhxlllllhlxlhxxlxxhlhxxhhxxlxlhxhhlllxxxxllxxxhxxxxxxxxxhxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxhxxxxxlxxxxlhxxlhxhhxxxxlxxxxxlxxxlxxxlxxxlxxlxxlxlxxxhxlhllhxxxlxlhxxxxlxxxhlxhxxxxxhlxxxxxxhxxxxxxhxxxxxxxxxxxlxxxlllllxlhlxxxlllllxlhxxlhllxhxxxxxxlxxxxlxhllllhllllhllhlllhhlllxllxhlxxllxxlhxlllxhxxhhxxhxxlxhhhhhhhhhhhhhhhhhxxxxhhhhhhhhhhhhhhhhxhxxxxxxxhhhhhhhhhhhhhhhhhxxxxxlhhhhhhhhhhhhhhxhhlxlxxlxxhxxhhhhhhhhhhhhhhhhhxxhxxlhxhxhhhhhhhhhhhhhxhhhhhxlhxhxhlxxxhhhhhhhhhhhhhhhhlhxhxhllxxxxxxxxxxxxxxlllxxxxxlxhxlxhxxxxxxxxhllllhlxlhlhlhlxhlhxlhlhlhlhlhllhllhhxhlllhxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxllllllllxxxxxxxxhhhhhhhlxxxxxxxxxllllllllxxxxxlxxlxxlxxlxxhxllxxlxxxxxxxxxxxxxxxxxxhhhhhxxxxhhhhhhhlllxxlllllxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxllxxxllxlxxlxlhhxxxxlllllllllllllllxhlxxxxxxxxxlxhllllllllllxllxlxxlllxllllllllxxllllllllxhhhhhhhhllllllllhxhhhhhhhhhxllllllllhhhhhhhhxhhhhhhhhxhhhhhhhhxhhhhhhhhhxxxxxxxxxxllllllllxxllllllllxxlxxxxxxxxxllllllllllllllllllllxxxxxxxxxlxllllllllxxxxxxxxxxxxllllllllxllllllllxllllllllxxhxlxllxxxxxxxhlxxlhllllllllxlllxlllllxxhhxxxllxxxxxxxxxhllllllllllxhxllllllllllllxxxxxxxxxllllllllxxllllllllxxxxhxxxxxxxxlllllllllhxhxhxhhhhxxxxxxxxxxxxxxxxhxxxxxxxxxxxxxxxxxllllllllllxlxxxlxxxxxxxxhhhllllllllllxxxxxxllllllllllllxlllxxlxllllllxxxxxxhhhhhhllxxllllllllllllllllxxxxxxxxxxxxllllllhllhhhhhhlllllhllhhhhlxhlxlhxlhxlhhlxllhhlllhlxhxxlllhxlhlxlhxxxxxxxxxllxxhllllllllllllllllllllllllllllllllxhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhlhhhllllllllllllllllllllllllllllllllllllhhlhhlllllhlhlllllllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhxxxxllllllllllllllllllllllllllllllllxxxxxxhllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllhhhhllllllllllllllllllllllllllllllllxlhhhlxhhlhhxhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhlllllllllllllllllllllllllllllllllxxlxxxxxxxxxlhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhxhlhllllllhllllllllllllllllllllllllllllllllllhhlllhlhlhhhhhhxxxlllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllxxhlhllllllxhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhxxxxxxxxllllllllllllllllllllllllllllllllxlhlhllhhxlxllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllllxxxxxlhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhlxlxllllllllllllllllllllllllllllllllllxxxllllhhxllxhhlhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllllxxxhhlhhhhhxhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhxxxxxxxlllllllllllllllllllllllllllllllllhllhhllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhxllllllllllllllllllllllllllllllllllllxxxxxxhhxxhhlhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllhhllhhhllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhxlllllllllllllllllllllllllllllllllllxllhhxhlxxhhlhhhhllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllhllllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhxxxxxxlxlllllllllllllllllllllllllllllllllxxxxxlhxxlhxxxllhllhlhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhxlllllllllllllllllllllllllllllllllxlxxlxllllhllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhlllllllllllllllllllllllllllllllllllllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhlhhxlllllllllllllllllllllllllllllllllxllhxllllhlhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhxllllllllllllllllllllllllllllllllllllxhhllhllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllxxlxxlhlhllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhlllllllllllllllllllllllllllllllllxxxxxxxxxxxxxxlhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhxlllllllllllllllllllllllllllllllllxxhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhlxxxxxxxxxxxxxxxxxllllllllllllllllllllllllllllllllllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllxlxxxxxhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllxxxxhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllhhhhlhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllhhhhlllxhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhlllllllllllllllllllllllllllllllllxlhhhhhxxxhxlxlhhhlhhlhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhlllllllllllllllllllllllllllllllllllllllhxlhlhlhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllxlxxxxhllllxlxxxxxxxxxxxxlhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllllxlxllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhxxxxlllllllllllllllllllllllllllllllllhlhlllllllllllllhlllllllllxlllllhlhlllllllllllllllllllllllllllllllllllllhlhhlhhhhlhhhhhllxhhlllhlhxhlhhllllhlxlhlhlxhhxhhhlhllhxhhlhlhlhxllxxxllhlhlhhhlhhlhlhhhlhllhhlhlllhlxhhlxhlhlhlhhxhllxlxhllllhhhxhllxhlxlhlhxhlxxlxxxhxhxhhlhxllxxlxllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhxlllllllllllllllllllllllllllllllllxlhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhlllllllllllhhllllllllllllllllllllllllllllllllhxhhxhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllxllxxhhhhhhhhhhhhhhlxxhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllxllllllxllllllllllllllllllllxhlxhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllhlhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhlxllllllllllllllllllllllllllllllllxxxxxxxxxxxxxxllhlxxlhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhxllllllllllllllllllllllllllllllllllhxhxhxlxhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllhlllllxllllllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllxxxxxxhhhllllllllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllxllllllllllllllllllllllllllllllllhllllllllhhlllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhlxlllllllllllllllllllllllllllllllllhllllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhlhhhhllllllllllllllllllllllllllllllllllhxxxxxxxlxxxxxxxxxxxxllllllhhhhlllxhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllllllllxlhhhxhhxlhhxxhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllxlhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllxxxxxxhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhxxxxxxllllllllllllllllllllllllllllllllxxxlllllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhlllllllllllllllllllllllllllllllllxhhlhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllllllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllllhxxxxxhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhlllllllllllllllllllllllllllllllllhxllllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhxlllllllllllllllllllllllllllllllllllllxlllllllllllllllllllllllllhhhhhhhhhhhhhhhhhhhhhhhhlhhhhlhhhhhxlhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllxlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllllllhhhlhhhhhllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhlllllllllllllllllllllllllllllllllllllllllllllllllllllllllllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhlhllllllllllllllllllllllllllllllllllllhhhhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllxlllxlhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhlllllllllllllllllllllllllllllllllllllllllllllllllllllllllhhhhhhhhhhhhhhhhhhhhhhhhxlhhhhxlxhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhlllllllllllllllllllllllllllllllllhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhlllllllllllllllllllllllllllllllllxlxxxxhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhlllllllllllllllllllllllllhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllxxxxlxxxlhlxxxxxxxhlxhhhhhhxxxxxllllllxhlllhhhhhhhhhhhhllllhlhlhlhlhlhlhlhlxxxxxxxlhhhhhhllllhlhlhlhlhllhhhhhlhllxxxxxxxxllllllllxxxxxxxxllllllllhhhhhhhhhhhhhhhhllllllllllllllllllhlhhhhhhhhlhhlllllxxxxxxxxxxxllllllllxxxxxxxxhhllhhllhhllhhllhhhhhhhhhhlllllllllllllllllhxhhxxxxxxxxllllllllxxxxxxxxhhllhhllhhllhhllhhhhhhhhhlllllllllllllllllhxhllllllllhhhhxxxxxxxxllllllllxxxxxxxxhllhhllhhllhhllhhhhhhhhhhhlllllllllhhhhhhhhlllllhllllllllllhxxxhhxxxxxxxxlllllllllxxxxxxxxxlhllhhllhhllhhllhhhhhhhhhllllllllllllllllllllllllllllllhhllxhhhhhhhhhhhhhxxxxxxxxllllllllhxxxxxxxxhllhhllhhllhhllhhhhhhhhhlllllllllllllllllllllxlllllllllhxxllxxxxxxxxxhllllllllhhhhhhhhhhhhhxxxxxxxxhllhhllhhllhhllhhhhhhhhhlllllllllllllllllhxhxxxxxxxxxllllllllxxxxxxxxxhllhhllhhllhhllhhhhhhhhhhllllllllhllllllllllhxhlxxxxxxxxxlhhhhhhhhhlxhhhhhhhhxxxxxxxxxxxxllxxxxllllllhhhhhhhhxxxxxxxxxxxxxxxhhhhhhhhhllllllllhhhhhhhhhhhhhllhhhhllllllxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxhhxxxxxxxxxxxxxxxxxxxxxxxxxhhhhhhhhhhhhhhllllhllllxhhlllllllllllllllhhxhxxxxhhllllllllllllllhllllxhxlxxhllllllllxlllllllllllllxxxxxxxxxhxhhhhhhhhxxxxxxxxlhhhhhhhhhhhhhhhhhhxxxxxxxxllllxxxxxxxxxhxxxxxxxxxxxxxxxxxxxhhhhhhhhlllxxxxxxxxlhhhhhhhhxhhhhhhhhhxxxhhhhhhhhllllllllxllllllllllllllllllhhhhhhhhlllxxxxxxxxlhhhhhhhhxhhhhhhhhhxhhhhhhhhllllllllhhhhhhhhhhhhhhhhhhhhhhhhxxxxxxxxhhhhhhhhxllllllllhhhhhhhhhhhhhhhhllllllllhhllllllllhhhlxxxxxxxxxhhhhhhhhhxhlxxxhhhhhhhhhllhhhhhhhhlllllllllllhxhhhllllllllhhhhhhllllxxxxxxxxlllhhhhhhhhllllllhhhhhhhhhlllxhhhhhhhhhxhhhhhhhhlllllllllxhhllllllllhhhhhhhhhhhhlxhllhhhhhhhhllllllxlxhxllllxxxxxxxxlhhhhhhhhxxxxxhhhhhhhhhxhhhhhhhhlllllllllllllllllllllllllllllllllllllllllllxxxxxxxxlhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhxhhhhhhhhhxxxhhhhhhhhllllllllxxllllllllllllllllllllllllllllllllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhxxxxxxxxhhhhhhhhllllllllllllllllhhhhhhhhlhhllhhhhhhhhhhhxlxxllhlllhhllhxllhlhxxhlhlhhhhhllhhlhhhllxhhhhhhhhhhxxxxxllllllhllhhhhhxlllhllhlhhllllllllllllxlllllllllhllhhllllllllllllllhhlllllllhllllllllllhllhhhhhllllllllllllllllllllllxllhhhhhhhhhhhhhhlhhllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh"
		};

		private bool _vramChanged = false;
		private bool _paletteRamChanged = false;
		private bool _spriteRamChanged = false;

		public frmMain()
		{
			InitializeComponent();

			CoreWrapper.initEmulator();
			CoreWrapper.reset(_resetStates[0]);
		}

		protected override void OnLoad(EventArgs e)
		{
			base.OnLoad(e);

			Step(1);

			StartEmulationThread();
		}

		protected override void OnClosed(EventArgs e)
		{
			CoreWrapper.release();
			base.OnClosed(e);
		}

		private void StartEmulationThread()
		{
			Task.Run(() => {
				while(true) {
					lock(_runLock) {
						while(_stepsToRun > 0) {
							UpdateRam();

							int stepsToRun = Math.Min(2550, _stepsToRun);
							Interlocked.Add(ref _stepsToRun, -stepsToRun);

							Stopwatch sw = new Stopwatch();
							sw.Start();
							CoreWrapper.step((UInt32)stepsToRun);
							sw.Stop();

							this.BeginInvoke((MethodInvoker)(() => {
								double emulatedHz = Stopwatch.Frequency / (double)sw.ElapsedTicks * stepsToRun / 2;
								lblHz.Text = emulatedHz.ToString("0");

								UpdateUI();
							}));
						}
					}

					if(_autoRun) {
						Interlocked.Add(ref _stepsToRun, 2550);
					} else {
						System.Threading.Thread.Sleep(50);
					}
				}
			});
		}

		private void UpdateRam()
		{
			if(_vramChanged) {
				CoreWrapper.setMemoryState(MemoryType.Vram, ((StaticByteProvider)hexVram.ByteProvider).Bytes.ToArray());
			}
			if(_paletteRamChanged) {
				CoreWrapper.setMemoryState(MemoryType.PaletteRam, ((StaticByteProvider)hexPaletteRam.ByteProvider).Bytes.ToArray());
			}
			if(_spriteRamChanged) {
				CoreWrapper.setMemoryState(MemoryType.SpriteRam, ((StaticByteProvider)hexSpriteRam.ByteProvider).Bytes.ToArray());
			}
			_vramChanged = false;
			_paletteRamChanged = false;
			_spriteRamChanged = false;
		}

		private void UpdateUI()
		{
			CoreWrapper.getState(ref state);
			lblHalfCycle.Text = state.halfcycle.ToString();
			lblPixel.Text = state.hpos.ToString();
			lblScanline.Text = state.vpos.ToString();

			UpdateMemoryViews();
			UpdateLogList();
		}

		private void UpdateMemoryViews()
		{
			StaticByteProvider vramBp = new StaticByteProvider(CoreWrapper.getMemoryState(MemoryType.Vram));
			StaticByteProvider paletteBp = new StaticByteProvider(CoreWrapper.getMemoryState(MemoryType.PaletteRam));
			StaticByteProvider spriteBp = new StaticByteProvider(CoreWrapper.getMemoryState(MemoryType.SpriteRam));

			hexVram.ByteProvider = vramBp;
			hexPaletteRam.ByteProvider = paletteBp;
			hexSpriteRam.ByteProvider = spriteBp;
			vramBp.ByteChanged += (index, e) => { _vramChanged = true; };
			paletteBp.ByteChanged += (index, e) => {
				//Mirror palette writes
				int i = (int)index;
				if(i == 0x10 || i == 0x14 || i == 0x18 || i == 0x1C) {
					paletteBp.WriteByte(i - 0x10, paletteBp.Bytes[i]);
				} else if(i == 0x00 || i == 0x04 || i == 0x08 || i == 0x0C) {
					paletteBp.WriteByte(i + 0x10, paletteBp.Bytes[i]);
				}
				_paletteRamChanged = true;
			};
			spriteBp.ByteChanged += (index, e) => { _spriteRamChanged = true; };
		}

		private void UpdateLogList()
		{
			lstLogView.BeginUpdate();

			if(_needColumnUpdate) {
				_needColumnUpdate = false;
				lstLogView.Clear();
				foreach(string column in _tracedColumns) {
					lstLogView.Columns.Add(column);
				}

				for(int i = 0; i < 100; i++) {
					ListViewItem item = new ListViewItem("");
					for(int j = 0; j < _tracedColumns.Count - 1; j++) {
						item.SubItems.Add("");
					}
					lstLogView.Items.Add(item);
				}
			}

			int pos = 0;
			int row = 0;
			bool endOfArray = false;
			while(row < 100) {
				for(int j = 0; j < _tracedColumns.Count; j++) {
					if(state.recentLog[pos] == -1) {
						endOfArray = true;
					}
					string newVal = (pos >= state.recentLog.Length || endOfArray) ? "" : state.recentLog[pos].ToString();
					if(lstLogView.Items[row].SubItems[j].Text != newVal) {
						lstLogView.Items[row].SubItems[j].Text = newVal;
					}
					pos++;
				}

				row++;
			}

			lstLogView.EndUpdate();
		}

		private void Stop()
		{
			btnRun.Text = "Run";
			_autoRun = false;
		}

		private void Step(UInt32 step)
		{
			Interlocked.Exchange(ref _stepsToRun, (int)step);
		}

		private void Reset(string state)
		{
			lock(_runLock) {
				CoreWrapper.reset(state);
				Step(1);
			}
		}

		private void btnRun_Click(object sender, EventArgs e)
		{
			if(_autoRun) {
				btnRun.Text = "Run";
				_autoRun = false;
			} else {
				btnRun.Text = "Stop";
				_autoRun = true;
			}
		}

		private void btnNextPixel_Click(object sender, EventArgs e)
		{
			Stop();
			Step(8);
		}

		private void btnNextScanline_Click(object sender, EventArgs e)
		{
			Stop();
			Step(2728);
		}

		private void btnNextFrame_Click(object sender, EventArgs e)
		{
			Stop();
			Step(714736);
		}

		private void btnReset_Click(object sender, EventArgs e)
		{
			if(radResetPowerOn.Checked) Reset("");
			else if(radResetPrerenderOdd.Checked) Reset(_resetStates[0]);
			else if(radResetPrerenderEven.Checked) Reset(_resetStates[1]);
			else if(radResetPostrenderOdd.Checked) Reset(_resetStates[2]);
		}

		private void btnSaveState_Click(object sender, EventArgs e)
		{
			using(SaveFileDialog sfd = new SaveFileDialog()) {
				sfd.Filter = "Save states (*.bin)|*.bin";
				if(sfd.ShowDialog() == DialogResult.OK) {
					lock(_runLock) {
						File.WriteAllBytes(sfd.FileName, CoreWrapper.getMemoryState(MemoryType.FullState));
						_vramChanged = false;
						_paletteRamChanged = false;
						_spriteRamChanged = false;
						Step(1);
					}
				}
			}
		}

		private void btnLoadState_Click(object sender, EventArgs e)
		{
			using(OpenFileDialog ofd = new OpenFileDialog()) {
				ofd.Filter = "Save states (*.bin)|*.bin";
				if(ofd.ShowDialog() == DialogResult.OK) {
					lock(_runLock) {
						CoreWrapper.setMemoryState(MemoryType.FullState, File.ReadAllBytes(ofd.FileName));
						_vramChanged = false;
						_paletteRamChanged = false;
						_spriteRamChanged = false;
						Step(1);
					}
				}
			}
		}

		private void btnResetVram_Click(object sender, EventArgs e)
		{
			UpdateRam();
			CoreWrapper.setMemoryState(MemoryType.Vram, new byte[0x3000]);
			UpdateMemoryViews();
		}

		private void btnResetSpriteRam_Click(object sender, EventArgs e)
		{
			UpdateRam();
			CoreWrapper.setMemoryState(MemoryType.SpriteRam, new byte[0x100]);
			UpdateMemoryViews();
		}

		private void btnResetPaletteRam_Click(object sender, EventArgs e)
		{
			UpdateRam();
			CoreWrapper.setMemoryState(MemoryType.PaletteRam, new byte[0x20]);
			UpdateMemoryViews();
		}
	}

	public struct EmulationState
	{
		public int halfcycle;
		public int hpos;
		public int vpos;
		public int vramaddr_v;
		public int vramAddr_t;
		public int vbl_flag;
		public int spr_overflow;
		public int spr0_hit;

		[MarshalAsAttribute(UnmanagedType.ByValArray, SizeConst = 10000, ArraySubType = UnmanagedType.I4)]
		public int[] recentLog;
	};

	public enum MemoryType
	{
		Vram = 0,
		PaletteRam = 1,
		SpriteRam = 2,
		FullState = 3,
	}

	public static class CoreWrapper
	{
		const string dllName = "Core2C02.dll";

		[DllImport(dllName)] public extern static void initEmulator();
		[DllImport(dllName)] public extern static void release();
		
		[DllImport(dllName)] public extern static void getState(ref EmulationState state);

		[DllImport(dllName)] public extern static void addTrace([MarshalAs(UnmanagedType.CustomMarshaler, MarshalTypeRef = typeof(UTF8Marshaler))]string addTrace);
		[DllImport(dllName)] public extern static void clearTrace();

		[DllImport(dllName)] public extern static void step(UInt32 halfCycleCount);
		[DllImport(dllName)] public extern static void reset([MarshalAs(UnmanagedType.CustomMarshaler, MarshalTypeRef = typeof(UTF8Marshaler))]string resetState);

		[DllImport(dllName, EntryPoint = "getMemoryState")] private static extern int getMemoryStateWrapper(MemoryType type, IntPtr buffer);
		public static byte[] getMemoryState(MemoryType type)
		{
			byte[] buffer = new byte[0xFFFF];
			GCHandle handle = GCHandle.Alloc(buffer, GCHandleType.Pinned);
			try {
				int memorySize = getMemoryStateWrapper(type, handle.AddrOfPinnedObject());
				Array.Resize(ref buffer, (int)memorySize);
			} finally {
				handle.Free();
			}
			return buffer;
		}

		[DllImport(dllName, EntryPoint = "setMemoryState")] private static extern void setMemoryStateWrapper(MemoryType type, IntPtr buffer);
		public static void setMemoryState(MemoryType type, byte[] data)
		{
			GCHandle handle = GCHandle.Alloc(data, GCHandleType.Pinned);
			try {
				setMemoryStateWrapper(type, handle.AddrOfPinnedObject());
			} finally {
				handle.Free();
			}
		}
	}

	public class UTF8Marshaler : ICustomMarshaler
	{
		static UTF8Marshaler _instance;

		public IntPtr MarshalManagedToNative(object managedObj)
		{
			if(managedObj == null) {
				return IntPtr.Zero;
			}
			if(!(managedObj is string)) {
				throw new MarshalDirectiveException("UTF8Marshaler must be used on a string.");
			}

			// not null terminated
			byte[] strbuf = Encoding.UTF8.GetBytes((string)managedObj);
			IntPtr buffer = Marshal.AllocHGlobal(strbuf.Length + 1);
			Marshal.Copy(strbuf, 0, buffer, strbuf.Length);

			// write the terminating null
			Marshal.WriteByte(buffer + strbuf.Length, 0);
			return buffer;
		}

		public object MarshalNativeToManaged(IntPtr pNativeData)
		{
			return GetStringFromIntPtr(pNativeData);
		}

		public void CleanUpNativeData(IntPtr pNativeData)
		{
			//Marshal.FreeHGlobal(pNativeData);
		}

		public void CleanUpManagedData(object managedObj)
		{
		}

		public int GetNativeDataSize()
		{
			return -1;
		}

		public static ICustomMarshaler GetInstance(string cookie)
		{
			if(_instance == null) {
				return _instance = new UTF8Marshaler();
			}
			return _instance;
		}

		public static string GetStringFromIntPtr(IntPtr pNativeData)
		{
			int offset = 0;
			byte b = 0;
			do {
				b = Marshal.ReadByte(pNativeData, offset);
				offset++;
			} while(b != 0);

			int length = offset - 1;

			// should not be null terminated
			byte[] strbuf = new byte[length];
			// skip the trailing null
			Marshal.Copy((IntPtr)pNativeData, strbuf, 0, length);
			string data = Encoding.UTF8.GetString(strbuf);
			return data;
		}
	}

	public class StaticByteProvider : DynamicByteProvider
	{
		public StaticByteProvider(byte[] data) : base(data) 
		{
		}

		public override bool SupportsInsertBytes()
		{
			return false;
		}

		public override bool SupportsDeleteBytes()
		{
			return false;
		}
	}
}
