using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Diagnostics;
using System.Drawing;
using System.IO;
using System.Runtime.InteropServices;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using System.Windows.Forms;
using Be.Windows.Forms;

namespace GUI
{
	public partial class frmMain : Form
	{
		private List<string> _tracedColumns = new List<string> { "cycle", "hpos", "vpos", "vbl_flag", "spr0_hit", "spr_overflow", "vramaddr_t", "vramaddr_v", "io_db", "io_ab", "io_rw", "io_ce", "rd", "wr", "ab", "ale", "db" };
		private bool _autoRun = false;
		private object _runLock = new object();
		private int _stepsToRun = 0;
		private bool _needColumnUpdate = true;
		private EmulationState _previousState = new EmulationState();
		private Task _emulationThread = null;
		private bool _stopFlag = false;
		private string _dumpPath;
		private bool _vramChanged = false;
		private bool _paletteRamChanged = false;
		private bool _spriteRamChanged = false;
		private int _refreshSpeed = 2000;
		private bool _logging = false;
		private byte[] _vramData;
		private byte[] _paletteData;
		private byte[] _spriteData;

		List<string> _resetStates = new List<string>() {
			/*resetStatePostrenderOdd*/ "xvgllhlllllllhxxxhhlllllxllllllhxxxhhlxlllllllllllhhhhlllllxhhhlllllllllhllllhxlhxxhxlllhxxxxhllxlxllxxxxlhlxxxlxllhlxhlhlxhxhlxlxxxxxxlxxxxxxxxxxxxxhhxhhxhllxxxxxlxxxxhxlhlxxxxxxhlxxxxxxxxxlhxhlllhhlxxxhhhxxxllxhxlxxxhllllhhlhhlllhxxllxlxhhhxlhlxhhxhxxhhhxxxlllxxxxxxxxxxhhlxxlllhllhxlxxlxxhxxlxxhxxlhxhhxlhlhllxhxxlllllllllllllxxlxlhllxxxxhxxlxlxxxhxxxxhhlxlxxlxhlxhhxxxxhxxlllxlhllxxxhxlllxxxxlllxxxxxxlxxxxxxxxhhxxxlxhhlxxlllhllhlllhllhllhllllhxlhlhlllxxlhlllhxxxlxxxxxllhhhlxxhllhhxlhlhhxxxlhxlhhxxxllllllhlxxxhhxlxxxlllxhhxxlxxlxxhllxxxhhlhhlhxxxllxxxxllhxxxxllxxxxxhlllxxxxxxxllxxxhlxxxxxxxlllxxlllxxxlxxlxllxllhlhlhlhllhhlhllxxxxlllxxxllxxxxxxlxxxhhxxxxlxlhlhxxhxhxxxxxxxlxhxxxxhlhhllhxlhxxxxxxxxxxhxhxxlxxhxxlllxxxxlxxxlxhhhxxlxxxxxxxlxlhxxxxllxxxxxlxxxxxxlxxxxxlhhhxxxxxxhxxxxxhxlhxxxxxxxxxxxllxxxlxhlllxlxlllxlxlllxhlllhhlllllllllllllllllllhlllhlxxlxxlllhlxllllllhhhhhhhhhxxxxxxxxlllllhhxxxxllhllllllllxllllhlxhlxxxxxxhxhxhxhxllhlhlxlllxllhlhllxlxxxhxxxxxxlxhxhhxxllllhhhhxlxlxllxhlxlxlxxxhhllxxhlxlxxxlhhxxxxxxxxxxlxxxhhxxlxllllxxhxxxxlxxxhllxxhhlxxxxxlxxxxlllxxxxxlxhxlxxlhxxxxllxlxxlxhllxhxxhxlxlxlhlhlxhxxxlxxllllhlxlhhxxlxhxllllxxllhxxlxlhxllxhxllxxlllhxlxhhhxxhxlxxhxhhxxxhxlxhlxxxxxlhxlxxxhhlxlxxxllhxxlxxxllxxxxxxxxllxxhxxhxhxhxxhhxhxhxxxlhxxhxlxlllxhlxxxhlhlxlllhhhxxhxhxhxhxhxhxxxxhxhlxxxxlhxxxhxxxxllhxxxxllhlxlxhxlhlxhlllxxxxlhhxxxhlhhxlxhxxxxxxxlllhhhhhhlxxxxlllhxlxxlxllxxllxxlxxxlhhlhhhlhhhhhhllhhhlhlhlhhlhlhlhhlhlhlhlhlhlhhhlhlhlhlhhxllhxxxxxxxxxlxxhxxxxxlxxxlhlxxhlxxxxlhlxhxxhlxxlxxlllxxhxllxlxllxhlxlxhlxhxllxhlhxxxlxxxhllxxxlhllxxxhllxxxhlhxlllllhlxlhxxlxxhlhxxhhxxlxlhxhhlllxxxxllxxxhxxxxxxxxxhxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxhxxxxxlxxxxlhxxlhxhhxxxxlxxxxxlxxxlxxxlxxxlxxhxxlxlxxxlxlhllhxxxlxlhxxxxlxxxhlxhxxxxxhlxxxxxxhxxxxxxhxxxxxxxxxxxlxxxlllllxlhlxxxlllllxlhxxlhllxhxxxxxxlxxxxlxhllllhllllhllhlllhhlllxllxhlxxllxxlhxlllxhxxhhxxhxxlxhhhhhhhhhhhhhhhhhxxxxhhhhhhhhhhhhhhhhxhxxxxxxxhhhhhhhhhhhhhhhhhxxxxxlhhhhhhhhhhhhhhxhhlxlxxlxxhxxhhhhhhhhhhhhhhhhhxxhxxlhxhxhhhhhhhhhhhhhxhhhhhxlhxhxhlxxxhhhhhhhhhhhhhhhhlhxhxhllxxxxxxxxxxxxxxlllxxxxxlxhxlxhxxxxxxxxhllllhlxlhlhlhlxhlhxlhlhlhlhlhllhllhhxhlllhxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxllllllllxxxxxxxxhhhhhhhlxxxxxxxxxllllllllxxxxxlxxlxxlxxlxxhxllxxlxxxxxxxxxxxxxxxxxxhhhhhxxxxhhhhhhhlllxxlllllxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxllxxxllxlxxlxlhhxxxxlllllllllllllllxhlxxxxxxxxxlxhllllllllllxllxlxxlllxllllllllxxllllllllxhhhhhhhhllllllllhxhhhhhhhhhxllllllllhhhhhhhhxhhhhhhhhxhhhhhhhhxhhhhhhhhhxxxxxxxxxxllllllllxxllllllllxxlxxxxxxxxxllllllllllllllllllllxxxxxxxxxlxllllllllxxxxxxxxxxxxllllllllxllllllllxllllllllxxhxlxllxxxxxxxhlxxlhllllllllxlllxlllllxxhhxxxllxxxxxxxxxhllllllllllxhxllllllllllllxxxxxxxxxllllllllxxllllllllxxxxhxxxxxxxxlllllllllhxhxhxhhhhxxxxxxxxxxxxxxxxhxxxxxxxxxxxxxxxxxllllllllllxlxxxlxxxxxxxxhhhllllllllllxxxxxxllllllllllllxlllxxlxllllllxxxxxxhhhhhhllxxllllllllllllllllxxxxxxxxxxxxllllllhllhhhhhhlllllhllhhhhlxhlxlhxlhxlhhlxlllhhhlllxhxxlhllxlhlxllxxxxxxxxxllxxhllllllllllllllllllllllllllllllllxhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhlllhhhllllllllllllllllllllllllllllllllllhhlhhlllllhlhlllllllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhxxxxllllllllllllllllllllllllllllllllxxxxxxhllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhlhhhhhllllllllllllllllllllllllllllllllxllhhlxhhllhxhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhlllllllllllllllllllllllllllllllllxxlxxxxxxxxxlhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhxhlhllllllhllllllllllllllllllllllllllllllllllhhlllhlhlhhhhhhxxxlllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllxxhlhllllllxhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhxxxxxxxxllllllllllllllllllllllllllllllllxllhllhhhxlxlhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhlllllllllllllllllllllllllllllllllxxxxxhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhlxlxllllllllllllllllllllllllllllllllllxxxllllhlxlhxhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhlhllllllllllllllllllllllllllllllllxxxhllhhhhhxhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhxxxxxxxlllllllllllllllllllllllllllllllllllhhhhlhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhxlllllllllllllllllllllllllllllllllhllxxxxxxhhxxhlhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllhhllhlllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhxlllllllllllllllllllllllllllllllllllxlhhhxhlxxhhlhhhlllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllhllhllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhxxxxxxlxlllllllllllllllllllllllllllllllllxxxxxllxxlhxxxllhllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhxlllllllllllllllllllllllllllllllllxlxxlxllllhllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhlllllllllllllllllllllllllllllllllllllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhlhhxlllllllllllllllllllllllllllllllllxllhxllllhlhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhxllllllllllllllllllllllllllllllllllllxhhllhllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllxxlxxlhlhllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhlllllllllllllllllllllllllllllllllxxxxxxxxxxxxxxlhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhxlllllllllllllllllllllllllllllllllxxhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhlxxxxxxxxxxxxxxxxxllllllllllllllllllllllllllllllllllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhlllllllllllllllllllllllllllllllllxlxxxxxhlhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllxxxxhllhhhhhlhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllhhlhlhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllhhhhlllxhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllxlhhhhhxxxlxhxhlhhhllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllhlllllllllllllllllllllllllllllllllllhxlhhlhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllxlxxxxhllllxlxxxxxxxxxxxxlhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllllxlxllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhxxxxlllllllllllllllllllllllllllllllllhlhlllllllllllllhlllllllllxlllllhlhllllllllllllllllllllllllllllllllhhhhllllhlhhhhlllhhhllxllhhlhhhxhlhhhhhhhlxlhlhlxhhxlhhllhlhxhhhhhllhxllxxxlhhlhlhhhlhhhhlhhhlhllhhlllllhlxlhlxhlhhhllhxhllxlxhllllhhhxhllxhlxlhlhxllxxhxxxhxhxhhlhxllxxlxllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhxlllllllllllllllllllllllllllllllllxlhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhlllllllllllhhllllllllllllllllllllllllllllllllhxhhxhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllxllxxhhhhhhhhhhhhhhlxxhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllxllllllxllllllllllllllllllllxhlxhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllhlhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhlxllllllllllllllllllllllllllllllllxxxxxxxxxxxxxxllhlxxhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhxhhllllllllllllllllllllllllllllllllhxhxhxlxhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllhlllllxllllllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllxxxxxxhhhllllllllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllxllllllllllllllllllllllllllllllllhllllllllhhlllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhlxlllllllllllllllllllllllllllllllllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhlllllllllllllllllllllllllllllllllllllllhxxxxxxxlxxxxxxxxxxxxlllllllllllllxhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllllllllxlhhhxhhxlhhxxhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllxlhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllxxxxxxhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhxxxxxxllllllllllllllllllllllllllllllllxxxlhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhlllllllllllllllllllllllllllllllllxhhlhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllllllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllllhxxxxxhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhlllllllllllllllllllllllllllllllllhxllllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhxlllllllllllllllllllllllllllllllllllllxlllllllllllllllllllllllllhhhhhhhhhhhhhhhhhhhhhhhhlhhhhlhhhhhxlhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllxlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllllllhhhlhhhhhllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhlllllllllllllllllllllllllllllllllllllllllllllllllllllllllllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhlhllllllllllllllllllllllllllllllllllllhhhhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllxlllxlhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhlllllllllllllllllllllllllllllllllllllllllllllllllllllllllhhhhhhhhhhhhhhhhhhhhhhhhxlhhhhxlxhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhlllllllllllllllllllllllllllllllllhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhlllllllllllllllllllllllllllllllllxlxxxxhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhlllllllllllllllllllllllllhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllxxxxlxxxlhlxxxxxxxhlxhhhhhhxxxxxllllllxhlllhhhhhhhhhhhhhhlhhlhlhlhlhlhlhlhlxxxxxxxlllhlhhllllhlhlhlhlhllhhhhhlhllxxxxxxxxllllllllxxxxxxxxllllllllhhhhhhhhhhhhhhhhllllllllllllllllllhlhhhhhhhhlhhlllllxxxxxxxxxxxllllllllxxxxxxxxhhllhhllhhllhhllhhhhhhhhhhlllllllllllllllllhxhhxxxxxxxxllllllllxxxxxxxxhhllhhllhhllhhllhhhhhhhhhlllllllllllllllllhxhllllllllhhhhxxxxxxxxllllllllxxxxxxxxhllhhllhhllhhllhhhhhhhhhhhlllllllllhhhhhhhhlllllhllllllllllhxxxhhxxxxxxxxlllllllllxxxxxxxxxlhllhhllhhllhhllhhhhhhhhhllllllllllllllllllllllllllllllhhllxhhhhhhhhhhhhhxxxxxxxxllllllllhxxxxxxxxhllhhllhhllhhllhhhhhhhhhlllllllllllllllllllllxlllllllllhxxllxxxxxxxxxhllllllllhhhhhhhhhhhhhxxxxxxxxhllhhllhhllhhllhhhhhhhhhlllllllllllllllllhxhxxxxxxxxxllllllllxxxxxxxxxhllhhllhhllhhllhhhhhhhhhhllllllllhllllllllllhxhlxxxxxxxxxlhhhhhhhhhlxhhhhhhhhxxxxxxxxxxxxllxxxxllllllhhhhhhhhxxxxxxxxxxxxxxxhhhhhhhhhllllllllhhhhhhhhhhhhhllhhhhllllllxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxhhxxxxxxxxxxxxxxxxxxxxxxxxxhhhhhhhhhhhhhhllllhllllxhhlllllllllllllllhhxhxxxxhhllllllllllllllhllllxhxlxxhllllllllxlllllllllllllxxxxxxxxxhxhhhhhhhhxxxxxxxxlhhhhhhhhhhhhhhhhhhxxxxxxxxllllxxxxxxxxxhxxxxxxxxxxxxxxxxxxxhhhhhhhhlllxxxxxxxxlhhhhhhhhxhhhhhhhhhxxxhhhhhhhhllllllllxllllllllllllllllllhhhhhhhhlllxxxxxxxxlhhhhhhhhxhhhhhhhhhxhhhhhhhhllllllllhhhhhhhhhhhhhhhhhhhhhhhhxxxxxxxxhhhhhhhhxllllllllhhhhhhhhhhhhhhhhllllllllhhllllllllhhhlxxxxxxxxxhhhhhhhhhxhlxxxhhhhhhhhhllhhhhhhhhlllllllllllhxhhhllllllllhhhhhhllllxxxxxxxxlllhhhhhhhhllllllhhhhhhhhhlllxhhhhhhhhhxhhhhhhhhlllllllllxhhllllllllhhhhhhhhhhhhlxhllhhhhhhhhllllllxlxhxllllxxxxxxxxlhhhhhhhhxxxxxhhhhhhhhhxhhhhhhhhlllllllllllllllllllllllllllllllllllllllllllxxxxxxxxlhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhxhhhhhhhhhxxxhhhhhhhhllllllllxxllllllllllllllllllllllllllllllllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhxxxxxxxxhhhhhhhhllllllllllllllllhhhhhhhhlhhllhhhhhhhhhhhxlxxllhlllhhllhxllhlhxxhlhlhhhhhllhhlhhhllxhhhhhhhhhhxxxxxllllllhllhhhhhxlllhllhlhhllllllllllllxlllllllllllhlhllhlllllllhhhhhhlllllllhllllllllllhlllhhhhllllllllllllllllllllllxllhhhhhhhhhhhhhhlhhllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh",
			/*resetStatePrerenderOdd */ "xvgllhlllllllhxxxhhlllllxllllllhxxxhhlxlllllllllllhhhhlllllxhhhlllllllllhllllhxlhxxhxlllhxxxxhllxlxllxxxxlhlxxxlxllhlxhlhlxhxlhxlxxxxxxlxxxxxxxxxxxxxhhxhlxhllxxxxxlxxxxhxlhlxxxxxxhlxxxxxxxxxllxhlllhhlxxxhhhxxxlhxhxlxxxhllllhhlhhlllhxxllxlxhhhxlhlxhhxhxxhhhxxxlllxxxxxxxxxxhhlxxlllhllhxlxxlxxhxxlxxhxxlhxhlxlhlhlhxhxxlllllllllllllxxlxlhllxxxxhxxlxlxxxhxxxxhhlxlxxlxhlxhhxxxxhxxlllxllllxxxhxlllxxxxlllxxxxxxhxxxxxxxxhhxxxlxlhhxxllllllhlllhllhllhllllhxlhlhlllxxlllllhxxxlxxxxxhllhhlxxhhhhhxlhllhxxxllxlhhxxxhlllllhlxxxhhxlxxxlllxllxxlxxlxxhhlxxxlllhhllxxxllxxxxlhhxxxxllxxxxxhhhlxxxxxxxllxxxllxxxxxxxlllxxlllxxxlxxlxllxllhlhlhlhllhllhlhxxxxlllxxxlhxxxxxxlxxxhhxxxxlxlhlhxxhxhxxxxxxxlxhxxxxhlhhllhxlhxxxxxxxxxxhxhxxlxxhxxlllxxxxlxxxlxhhhxxlxxxxxxxlxlhxxxxlhxxxxxlxxxxxxlxxxxxlhhhxxxxxxhxxxxxhxlhxxxxxxxxxxxllxxxlxhhhhxlxlllxlxlllxhlllhllllllllllllllllhllllhhlhlxxlxxlllllxllllhlhhhhhhhhhxxxxxxxxlllllhlxxxxllhllllllllxllllhlxhlxxxxxxhxhxhxhxlhlhllxlllxlhhlhllxlxxxhxxxxxxlxhxhhxxhhhhhlhlxlxlxllxhlxlxlxxxhhllxxhlxlxxxllhxxxxxxxxxxlxxxhhxxlxlhlhxxhxxxxlxxxhhlxxlhlxxxxxlxxxxlllxxxxxlxhxlxxlhxxxxllxlxxlxhlhxhxxhxlxlxlhlhlxhxxxlxxllllhlxlhhxxlxhxllllxxllhxxlxlhxllxhxllxxlllhxlxhhhxxhxlxxhxhhxxxhxlxhlxxxxxlhxlxxxhhlxlxxxllhxxlxxxllxxxxxxxxllxxhxxhxhxhxxhhxhxhxxxlhxxhxlxlllxhlxxxhlhlxllllhhxxhxhxhxhxhxhxxxxhxhlxxxxlhxxxhxxxxllhxxxxllhlxlxhxlhlxhlllxxxxlhlxxxhlhhxlxhxxxxxxxlllhhhhhhlxxxxlllhxlxxlxllxxllxxlxxxlhhlhhhlhhhhhhllhhhlhlhlhhlhlhlhhlhlhlhlhlhlhhhlhlhlhlhhxllhxxxxxxxxxlxxhxxxxxlxxxlhlxxhlxxxxlhlxhxxhlxxlxxlllxxhxllxlxllxhlxlxhlxhxllxhlhxxxlxxxhllxxxlhllxxxhllxxxhlhxlllllhlxlhxxlxxhlhxxhhxxlxlhxhhlllxxxxllxxxhxxxxxxxxxhxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxhxxxxxlxxxxlhxxlhxhhxxxxlxxxxxlxxxlxxxlxxxlxxhxxlxlxxxlxlhllhxxxlxlhxxxxlxxxhlxhxxxxxhlxxxxxxhxxxxxxhxxxxxxxxxxxlxxxlllllxlhlxxxlllllxlhxxlhllxhxxxxxxlxxxxlxhllllhllllhllhlllhhlllxllxhlxxllxxlhxlllxhxxhhxxhxxlxhhhhhhhhhhhhhhhhhxxxxhhhhhhhhhhhhhhhhxhxxxxxxxhhhhhhhhhhhhhhhhhxxxxxlhhhhhhhhhhhhhhxhhlxlxxlxxhxxhhhhhhhhhhhhhhhhhxxhxxlhxhxhhhhhhhhhhhhhxhhhhhxlhxhxhlxxxhhhhhhhhhhhhhhhhlhxhxhllxxxxxxxxxxxxxxlllxxxxxlxhxlxhxxxxxxxxhllllhlxlhlhlhlxhlhxlhlhlhlhlhllhllhhxhlllhxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxllllllllxxxxxxxxhhhhhhhlxxxxxxxxxllllllllxxxxxlxxlxxlxxlxxhxllxxlxxxxxxxxxxxxxxxxxxhhhhhxxxxhhhhhhhlllxxlllllxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxllxxxllxlxxlxlhhxxxxlllllllllllllllxhlxxxxxxxxxlxhllllllllllxllxlxxlllxllllllllxxllllllllxhhhhhhhhllllllllhxhhhhhhhhhxllllllllhhhhhhhhxhhhhhhhhxhhhhhhhhxhhhhhhhhhxxxxxxxxxxllllllllxxllllllllxxlxxxxxxxxxllllllllllllllllllllxxxxxxxxxlxllllllllxxxxxxxxxxxxllllllllxllllllllxllllllllxxhxlxllxxxxxxxhlxxlhllllllllxlllxlllllxxhhxxxllxxxxxxxxxhllllllllllxhxllllllllllllxxxxxxxxxllllllllxxllllllllxxxxhxxxxxxxxlllllllllhxhxhxhhhhxxxxxxxxxxxxxxxxhxxxxxxxxxxxxxxxxxllllllllllxlxxxlxxxxxxxxhhhllllllllllxxxxxxllllllllllllxlllxxlxllllllxxxxxxhhhhhhllxxllllllllllllllllxxxxxxxxxxxxllllllhllhhhhhhlllllhllhhhhlxhlxlhxlhxlhhlxlllhhhlllxhxxlllhxlhlxlhxxxxxxxxxllxxhllllllllllllllllllllllllllllllllxhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhlllhhhllllllllllllllllllllllllllllllllllhhlhhlllllhlhlllllllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhxxxxllllllllllllllllllllllllllllllllxxxxxxhllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllhhhhllllllllllllllllllllllllllllllllxlhhhlxhhlhhxhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhlllllllllllllllllllllllllllllllllxxlxxxxxxxxxlhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhxhlhllllllhllllllllllllllllllllllllllllllllllhhlllhlhlhhhhhhxxxlllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllxxhlhllllllxhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhxxxxxxxxllllllllllllllllllllllllllllllllxlhlhllhhxlxllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllllxxxxxlhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhlxlxllllllllllllllllllllllllllllllllllxxxllllhhxllxhhlhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllllxxxhhlhhhhhxhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhxxxxxxxlllllllllllllllllllllllllllllllllhllhhllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhxllllllllllllllllllllllllllllllllllllxxxxxxhhxxhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllhhllhhlllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhxlllllllllllllllllllllllllllllllllllxllhhxhlxxhhlhhhhllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllhllllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhxxxxxxlxlllllllllllllllllllllllllllllllllxxxxxlhxxlhxxxllhllhlhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhxlllllllllllllllllllllllllllllllllxlxxlxllllhllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhlllllllllllllllllllllllllllllllllllllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhlhhxlllllllllllllllllllllllllllllllllxllhxllllhlhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhxllllllllllllllllllllllllllllllllllllxhhllhllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllxxlxxlhlhllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhlllllllllllllllllllllllllllllllllxxxxxxxxxxxxxxlhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhxlllllllllllllllllllllllllllllllllxxhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhlxxxxxxxxxxxxxxxxxllllllllllllllllllllllllllllllllllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllxlxxxxxhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllxxxxhhhhhlhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllhhhhlllxhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhlllllllllllllllllllllllllllllllllxlhhhhhxxxhxlxlhhhlhhlhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhlllllllllllllllllllllllllllllllllllllllhxlhllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllxlxxxxhllllxlxxxxxxxxxxxxlhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllllxlxllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhxxxxlllllllllllllllllllllllllllllllllhlhlllllllllllllhlllllllllxlllllhlhlllllllllllllllllllllllllllllllllllllhlhhlhhhhlhhhhhllxhhlllhlhxhlhhllllhlxlhlhlxhhxhhhlhllhxhhlhlhlhxllxxxllhlhlhhhlhhlhlhhhlhllhhlhlllhlxhhlxhlhlhlhhxhllxlxhllllhhhxhllxhlxlhlhxhlxxlxxxhxhxhhlhxllxxlxllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhxlllllllllllllllllllllllllllllllllxlhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhlllllllllllhhllllllllllllllllllllllllllllllllhxhhxhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllxllxxhhhhhhhhhhhhhhlxxhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllxllllllxllllllllllllllllllllxhlxhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllhlhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhlxllllllllllllllllllllllllllllllllxxxxxxxxxxxxxxllhlxxlhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhxllllllllllllllllllllllllllllllllllhxhxhxlxhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllhlllllxllllllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllxxxxxxhhhllllllllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllxllllllllllllllllllllllllllllllllhllllllllhhlllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhlxlllllllllllllllllllllllllllllllllhllllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhlhhhhllllllllllllllllllllllllllllllllllhxxxxxxxlxxxxxxxxxxxxllllllhhhhlllxhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllllllllxlhhhxhhxlhhxxhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllxlhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllxxxxxxhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhxxxxxxllllllllllllllllllllllllllllllllxxxlllllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhlllllllllllllllllllllllllllllllllxhhlhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllllllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllllhxxxxxhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhlllllllllllllllllllllllllllllllllhxllllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhxlllllllllllllllllllllllllllllllllllllxlllllllllllllllllllllllllhhhhhhhhhhhhhhhhhhhhhhhhlhhhhlhhhhhxlhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllxlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllllllhhhlhhhhhllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhlllllllllllllllllllllllllllllllllllllllllllllllllllllllllllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhlhllllllllllllllllllllllllllllllllllllhhhhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllxlllxlhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhlllllllllllllllllllllllllllllllllllllllllllllllllllllllllhhhhhhhhhhhhhhhhhhhhhhhhxlhhhhxlxhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhlllllllllllllllllllllllllllllllllhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhlllllllllllllllllllllllllllllllllxlxxxxhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhlllllllllllllllllllllllllhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllxxxxlxxxlhlxxxxxxxhlxhhhhhhxxxxxllllllxhlllhhhhhhhhhhhhlhllhlhlhlhlhlhlhlhlxxxxxxxlhlhhhhllllhlhlhlhlhllhhhhhlhllxxxxxxxxllllllllxxxxxxxxllllllllhhhhhhhhhhhhhhhhllllllllllllllllllhlhhhhhhhhlhhlllllxxxxxxxxxxxllllllllxxxxxxxxhhllhhllhhllhhllhhhhhhhhhhlllllllllllllllllhxhhxxxxxxxxllllllllxxxxxxxxhhllhhllhhllhhllhhhhhhhhhlllllllllllllllllhxhllllllllhhhhxxxxxxxxllllllllxxxxxxxxhllhhllhhllhhllhhhhhhhhhhhlllllllllhhhhhhhhlllllhllllllllllhxxxhhxxxxxxxxlllllllllxxxxxxxxxlhllhhllhhllhhllhhhhhhhhhllllllllllllllllllllllllllllllhhllxhhhhhhhhhhhhhxxxxxxxxllllllllhxxxxxxxxhllhhllhhllhhllhhhhhhhhhlllllllllllllllllllllxlllllllllhxxllxxxxxxxxxhllllllllhhhhhhhhhhhhhxxxxxxxxhllhhllhhllhhllhhhhhhhhhlllllllllllllllllhxhxxxxxxxxxllllllllxxxxxxxxxhllhhllhhllhhllhhhhhhhhhhllllllllhllllllllllhxhlxxxxxxxxxlhhhhhhhhhlxhhhhhhhhxxxxxxxxxxxxllxxxxllllllhhhhhhhhxxxxxxxxxxxxxxxhhhhhhhhhllllllllhhhhhhhhhhhhhllhhhhllllllxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxhhxxxxxxxxxxxxxxxxxxxxxxxxxhhhhhhhhhhhhhhllllhllllxhhlllllllllllllllhhxhxxxxhhllllllllllllllhllllxhxlxxhllllllllxlllllllllllllxxxxxxxxxhxhhhhhhhhxxxxxxxxlhhhhhhhhhhhhhhhhhhxxxxxxxxllllxxxxxxxxxhxxxxxxxxxxxxxxxxxxxhhhhhhhhlllxxxxxxxxlhhhhhhhhxhhhhhhhhhxxxhhhhhhhhllllllllxllllllllllllllllllhhhhhhhhlllxxxxxxxxlhhhhhhhhxhhhhhhhhhxhhhhhhhhllllllllhhhhhhhhhhhhhhhhhhhhhhhhxxxxxxxxhhhhhhhhxllllllllhhhhhhhhhhhhhhhhllllllllhhllllllllhhhlxxxxxxxxxhhhhhhhhhxhlxxxhhhhhhhhhllhhhhhhhhlllllllllllhxhhhllllllllhhhhhhllllxxxxxxxxlllhhhhhhhhllllllhhhhhhhhhlllxhhhhhhhhhxhhhhhhhhlllllllllxhhllllllllhhhhhhhhhhhhlxhllhhhhhhhhllllllxlxhxllllxxxxxxxxlhhhhhhhhxxxxxhhhhhhhhhxhhhhhhhhlllllllllllllllllllllllllllllllllllllllllllxxxxxxxxlhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhxhhhhhhhhhxxxhhhhhhhhllllllllxxllllllllllllllllllllllllllllllllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhxxxxxxxxhhhhhhhhllllllllllllllllhhhhhhhhlhhllhhhhhhhhhhhxlxxllhlllhhllhxllhlhxxhlhlhhhhhllhhlhhhllxhhhhhhhhhhxxxxxllllllhllhhhhhxlllhllhlhhllllllllllllxllllllllllllhhllllllllllllllhhlllllllhllllllllllhlllhhhhllllllllllllllllllllllxllhhhhhhhhhhhhhhlhhllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh",
			/*resetStatePrerenderEven*/ "xvgllhlllllllhxxxhhlllllxllllllhxxxhhlxlllllllllllhhhhlllllxhhhlllllllllhllllhxlhxxhxlllhxxxxhllxlxllxxxxlhlxxxlxllhlxhlhlxhxlhxhxxxxxxlxxxxxxxxxxxxxhhxhlxhllxxxxxlxxxxhxlhlxxxxxxhlxxxxxxxxxllxllhhhllxxxhhhxxxlhxhxlxxxhllllhlhhllhhhxxllxlxhhhxlhlxhhxhxxhhhxxxlllxxxxxxxxxxhhlxxlllhllhxlxxlxxhxxlxxhxxlhxhlxlhlhlhxhxxlllllllllllllxxlxlhllxxxxhxxlxlxxxhxxxxhhlxlxxlxhlxhhxxxxhxxlllxllllxxxhxlllxxxxlllxxxxxxhxxxxxxxxhhxxxlxlhhxxllllllhlllhllhllhllllhxlhlhlllxxlllllhxxxlxxxxxhllhhlxxhhhhhxlhllhxxxllxlhhxxxhlllllhlxxxhhxlxxxlllxllxxlxxlxxhhlxxxlllhhllxxxllxxxxlhhxxxxllxxxxxhhhlxxxxxxxllxxxllxxxxxxxlllxxlllxxxlxxlxllxllhlhlhlhllhllhlhxxxxlllxxxlhxxxxxxlxxxhhxxxxlxlhlhxxhxhxxxxxxxlxhxxxxhlhhllhxlhxxxxxxxxxxhxhxxlxxhxxlllxxxxlxxxlxhhhxxlxxxxxxxlxlhxxxxlhxxxxxlxxxxxxlxxxxxlhhhxxxxxxhxxxxxhxlhxxxxxxxxxxxllxxxlxhhhhxlxlllxlxlllxhlllhllllllllllllllllhllllhhlhlxxlxxlllllxllllhlhhhhhhhhhxxxxxxxxlllllhhxxxxllhllllllllxlllhhlxhlxxxxxxhxhxhxhxlhlhllxlllxlhhlhllxlxxxhxxxxxxlxhxhhxxhhhhhlhlxlxlxllxhlxlxlxxxhhllxxhlxlxxxllhxxxxxxxxxxlxxxhhxxlxlhlhxxhxxxxlxxxhhlxxlhlxxxxxlxxxxlllxxxxxlxhxlxxlhxxxxllxlxxlxhlhxhxxhxlxlxlhlhlxhxxxlxxllllhlxlhhxxlxhxllllxxllhxxlxlhxllxhxllxxlllhxlxhhhxxhxlxxhxhhxxxhxlxhlxxxxxlhxlxxxhhlxlxxxllhxxlxxxllxxxxxxxxllxxhxxhxhxhxxhhxhxhxxxlhxxhxlxlllxhlxxxhlhlxllllhhxxhxhxhxhxhxhxxxxhxhlxxxxlhxxxhxxxxllhxxxxllhlxlxhxlhlxhlllxxxxlhlxxxhlhhxlxhxxxxxxxlllhhhhhhlxxxxlllhxlxxlxllxxllxxlxxxlhhlhhhlhhhhhhllhhhlhlhlhhlhlhlhhlhlhlhlhlhlhhhlhlhlhlhhxllhxxxxxxxxxlxxhxxxxxlxxxlhlxxhlxxxxlhlxhxxhlxxlxxlllxxhxllxlxllxhlxlxhlxhxllxhlhxxxlxxxhllxxxlhllxxxhllxxxhlhxlllllhlxlhxxlxxhlhxxhhxxlxlhxhhlllxxxxllxxxhxxxxxxxxxhxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxhxxxxxlxxxxlhxxlhxhhxxxxlxxxxxlxxxlxxxlxxxlxxlxxlxlxxxhxlhllhxxxlxlhxxxxlxxxhlxhxxxxxhlxxxxxxhxxxxxxhxxxxxxxxxxxlxxxlllllxlhlxxxlllllxlhxxlhllxhxxxxxxlxxxxlxhllllhllllhllhlllhhlllxllxhlxxllxxlhxlllxhxxhhxxhxxlxhhhhhhhhhhhhhhhhhxxxxhhhhhhhhhhhhhhhhxhxxxxxxxhhhhhhhhhhhhhhhhhxxxxxlhhhhhhhhhhhhhhxhhlxlxxlxxhxxhhhhhhhhhhhhhhhhhxxhxxlhxhxhhhhhhhhhhhhhxhhhhhxlhxhxhlxxxhhhhhhhhhhhhhhhhlhxhxhllxxxxxxxxxxxxxxlllxxxxxlxhxlxhxxxxxxxxhllllhlxlhlhlhlxhlhxlhlhlhlhlhllhllhhxhlllhxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxllllllllxxxxxxxxhhhhhhhlxxxxxxxxxllllllllxxxxxlxxlxxlxxlxxhxllxxlxxxxxxxxxxxxxxxxxxhhhhhxxxxhhhhhhhlllxxlllllxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxllxxxllxlxxlxlhhxxxxlllllllllllllllxhlxxxxxxxxxlxhllllllllllxllxlxxlllxllllllllxxllllllllxhhhhhhhhllllllllhxhhhhhhhhhxllllllllhhhhhhhhxhhhhhhhhxhhhhhhhhxhhhhhhhhhxxxxxxxxxxllllllllxxllllllllxxlxxxxxxxxxllllllllllllllllllllxxxxxxxxxlxllllllllxxxxxxxxxxxxllllllllxllllllllxllllllllxxhxlxllxxxxxxxhlxxlhllllllllxlllxlllllxxhhxxxllxxxxxxxxxhllllllllllxhxllllllllllllxxxxxxxxxllllllllxxllllllllxxxxhxxxxxxxxlllllllllhxhxhxhhhhxxxxxxxxxxxxxxxxhxxxxxxxxxxxxxxxxxllllllllllxlxxxlxxxxxxxxhhhllllllllllxxxxxxllllllllllllxlllxxlxllllllxxxxxxhhhhhhllxxllllllllllllllllxxxxxxxxxxxxllllllhllhhhhhhlllllhllhhhhlxhlxlhxlhxlhhlxllhhlllhlxhxxlllhxlhlxlhxxxxxxxxxllxxhllllllllllllllllllllllllllllllllxhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhlhhhllllllllllllllllllllllllllllllllllllhhlhhlllllhlhlllllllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhxxxxllllllllllllllllllllllllllllllllxxxxxxhllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllhhhhllllllllllllllllllllllllllllllllxlhhhlxhhlhhxhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhlllllllllllllllllllllllllllllllllxxlxxxxxxxxxlhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhxhlhllllllhllllllllllllllllllllllllllllllllllhhlllhlhlhhhhhhxxxlllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllxxhlhllllllxhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhxxxxxxxxllllllllllllllllllllllllllllllllxlhlhllhhxlxllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllllxxxxxlhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhlxlxllllllllllllllllllllllllllllllllllxxxllllhhxllxhhlhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllllxxxhhlhhhhhxhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhxxxxxxxlllllllllllllllllllllllllllllllllhllhhllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhxllllllllllllllllllllllllllllllllllllxxxxxxhhxxhhlhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllhhllhhhllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhxlllllllllllllllllllllllllllllllllllxllhhxhlxxhhlhhhhllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllhllllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhxxxxxxlxlllllllllllllllllllllllllllllllllxxxxxlhxxlhxxxllhllhlhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhxlllllllllllllllllllllllllllllllllxlxxlxllllhllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhlllllllllllllllllllllllllllllllllllllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhlhhxlllllllllllllllllllllllllllllllllxllhxllllhlhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhxllllllllllllllllllllllllllllllllllllxhhllhllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllxxlxxlhlhllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhlllllllllllllllllllllllllllllllllxxxxxxxxxxxxxxlhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhxlllllllllllllllllllllllllllllllllxxhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhlxxxxxxxxxxxxxxxxxllllllllllllllllllllllllllllllllllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllxlxxxxxhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllxxxxhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllhhhhlhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllhhhhlllxhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhlllllllllllllllllllllllllllllllllxlhhhhhxxxhxlxlhhhlhhlhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhlllllllllllllllllllllllllllllllllllllllhxlhlhlhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllxlxxxxhllllxlxxxxxxxxxxxxlhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllllxlxllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhxxxxlllllllllllllllllllllllllllllllllhlhlllllllllllllhlllllllllxlllllhlhlllllllllllllllllllllllllllllllllllllhlhhlhhhhlhhhhhllxhhlllhlhxhlhhllllhlxlhlhlxhhxhhhlhllhxhhlhlhlhxllxxxllhlhlhhhlhhlhlhhhlhllhhlhlllhlxhhlxhlhlhlhhxhllxlxhllllhhhxhllxhlxlhlhxhlxxlxxxhxhxhhlhxllxxlxllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhxlllllllllllllllllllllllllllllllllxlhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhlllllllllllhhllllllllllllllllllllllllllllllllhxhhxhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllxllxxhhhhhhhhhhhhhhlxxhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllxllllllxllllllllllllllllllllxhlxhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllhlhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhlxllllllllllllllllllllllllllllllllxxxxxxxxxxxxxxllhlxxlhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhxllllllllllllllllllllllllllllllllllhxhxhxlxhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllhlllllxllllllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllxxxxxxhhhllllllllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllxllllllllllllllllllllllllllllllllhllllllllhhlllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhlxlllllllllllllllllllllllllllllllllhllllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhlhhhhllllllllllllllllllllllllllllllllllhxxxxxxxlxxxxxxxxxxxxllllllhhhhlllxhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllllllllxlhhhxhhxlhhxxhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllxlhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllxxxxxxhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhxxxxxxllllllllllllllllllllllllllllllllxxxlllllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhlllllllllllllllllllllllllllllllllxhhlhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllllllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllllhxxxxxhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhlllllllllllllllllllllllllllllllllhxllllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhxlllllllllllllllllllllllllllllllllllllxlllllllllllllllllllllllllhhhhhhhhhhhhhhhhhhhhhhhhlhhhhlhhhhhxlhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllxlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllllllhhhlhhhhhllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhlllllllllllllllllllllllllllllllllllllllllllllllllllllllllllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhlhllllllllllllllllllllllllllllllllllllhhhhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllxlllxlhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhlllllllllllllllllllllllllllllllllllllllllllllllllllllllllhhhhhhhhhhhhhhhhhhhhhhhhxlhhhhxlxhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhlllllllllllllllllllllllllllllllllhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhlllllllllllllllllllllllllllllllllxlxxxxhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhlllllllllllllllllllllllllhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhllllllllllllllllllllllllllllllllxxxxlxxxlhlxxxxxxxhlxhhhhhhxxxxxllllllxhlllhhhhhhhhhhhhllllhlhlhlhlhlhlhlhlxxxxxxxlhhhhhhllllhlhlhlhlhllhhhhhlhllxxxxxxxxllllllllxxxxxxxxllllllllhhhhhhhhhhhhhhhhllllllllllllllllllhlhhhhhhhhlhhlllllxxxxxxxxxxxllllllllxxxxxxxxhhllhhllhhllhhllhhhhhhhhhhlllllllllllllllllhxhhxxxxxxxxllllllllxxxxxxxxhhllhhllhhllhhllhhhhhhhhhlllllllllllllllllhxhllllllllhhhhxxxxxxxxllllllllxxxxxxxxhllhhllhhllhhllhhhhhhhhhhhlllllllllhhhhhhhhlllllhllllllllllhxxxhhxxxxxxxxlllllllllxxxxxxxxxlhllhhllhhllhhllhhhhhhhhhllllllllllllllllllllllllllllllhhllxhhhhhhhhhhhhhxxxxxxxxllllllllhxxxxxxxxhllhhllhhllhhllhhhhhhhhhlllllllllllllllllllllxlllllllllhxxllxxxxxxxxxhllllllllhhhhhhhhhhhhhxxxxxxxxhllhhllhhllhhllhhhhhhhhhlllllllllllllllllhxhxxxxxxxxxllllllllxxxxxxxxxhllhhllhhllhhllhhhhhhhhhhllllllllhllllllllllhxhlxxxxxxxxxlhhhhhhhhhlxhhhhhhhhxxxxxxxxxxxxllxxxxllllllhhhhhhhhxxxxxxxxxxxxxxxhhhhhhhhhllllllllhhhhhhhhhhhhhllhhhhllllllxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxhhxxxxxxxxxxxxxxxxxxxxxxxxxhhhhhhhhhhhhhhllllhllllxhhlllllllllllllllhhxhxxxxhhllllllllllllllhllllxhxlxxhllllllllxlllllllllllllxxxxxxxxxhxhhhhhhhhxxxxxxxxlhhhhhhhhhhhhhhhhhhxxxxxxxxllllxxxxxxxxxhxxxxxxxxxxxxxxxxxxxhhhhhhhhlllxxxxxxxxlhhhhhhhhxhhhhhhhhhxxxhhhhhhhhllllllllxllllllllllllllllllhhhhhhhhlllxxxxxxxxlhhhhhhhhxhhhhhhhhhxhhhhhhhhllllllllhhhhhhhhhhhhhhhhhhhhhhhhxxxxxxxxhhhhhhhhxllllllllhhhhhhhhhhhhhhhhllllllllhhllllllllhhhlxxxxxxxxxhhhhhhhhhxhlxxxhhhhhhhhhllhhhhhhhhlllllllllllhxhhhllllllllhhhhhhllllxxxxxxxxlllhhhhhhhhllllllhhhhhhhhhlllxhhhhhhhhhxhhhhhhhhlllllllllxhhllllllllhhhhhhhhhhhhlxhllhhhhhhhhllllllxlxhxllllxxxxxxxxlhhhhhhhhxxxxxhhhhhhhhhxhhhhhhhhlllllllllllllllllllllllllllllllllllllllllllxxxxxxxxlhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhxhhhhhhhhhxxxhhhhhhhhllllllllxxllllllllllllllllllllllllllllllllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhxxxxxxxxhhhhhhhhllllllllllllllllhhhhhhhhlhhllhhhhhhhhhhhxlxxllhlllhhllhxllhlhxxhlhlhhhhhllhhlhhhllxhhhhhhhhhhxxxxxllllllhllhhhhhxlllhllhlhhllllllllllllxlllllllllhllhhllllllllllllllhhlllllllhllllllllllhllhhhhhllllllllllllllllllllllxllhhhhhhhhhhhhhhlhhllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh"
		};

		private byte[] _initialProgram = new byte[] {
			0x20, 0x00, // $00 -> $2000
			0x21, 0x00, // $00 -> $2001
			0x23, 0x00, // $00 -> $2003, sprite DMA follows
			0x24, 0xFF, 0x00, 0x18, 0x24, 0xFF, 0x00, 0x18, 0x24, 0xFF, 0x00, 0x18, 0x24, 0xFF, 0x00, 0x18,
			0x23, 0xFC, // $FC -> $2003 - set last sprite
			0x24, 0xFF, 0x00, 0x18, 0x24, 0xFF, 0x00, 0x18, 0x24, 0xFF, 0x00, 0x18, 0x24, 0xFF, 0x00, 0x18,
			0x32, 0x00, // read $2002
			0x25, 0x00, // $00 -> $2005
			0x25, 0x00, // $00 -> $2005
			0x20, 0x90, // $90 -> $2000
			0x21, 0x1E,	// $1E -> $2001
		};

		public frmMain()
		{
			InitializeComponent();

			_dumpPath = Path.Combine(Path.GetDirectoryName(System.Reflection.Assembly.GetEntryAssembly().Location), "Dumps");
			Directory.CreateDirectory(_dumpPath);
		}

		protected override void OnLoad(EventArgs e)
		{
			base.OnLoad(e);
			
			hexProgram.ByteProvider = new DynamicByteProvider(_initialProgram);
			hexProgram.ByteProvider.Changed += (s, evt) => {
				lock(_runLock) {
					CoreWrapper.setProgram(((DynamicByteProvider)hexProgram.ByteProvider).Bytes.ToArray());
				}
			};
			
			CoreWrapper.setProgram(_initialProgram);
			CoreWrapper.initEmulator();
			CoreWrapper.reset(_resetStates[0]);

			cboRefreshSpeed.SelectedIndex = 1;

			Step(1);

			StartEmulationThread();
		}

		protected override void OnClosed(EventArgs e)
		{
			Stop();
			_stopFlag = true;
			if(_emulationThread != null) {
				_emulationThread.Wait();
			}
			CoreWrapper.release();
			base.OnClosed(e);
		}

		private void StartEmulationThread()
		{
			_emulationThread = Task.Run(() => {
				while(!_stopFlag) {
					while(!_stopFlag && _stepsToRun > 0) {
						UpdateRam();

						int stepsToRun = Math.Min(_refreshSpeed, _stepsToRun);
						Interlocked.Add(ref _stepsToRun, -stepsToRun);

						Stopwatch sw = new Stopwatch();
						lock(_runLock) {
							sw.Start();
							CoreWrapper.step((UInt32)stepsToRun);
							CoreWrapper.getState(ref _previousState);
							_vramData = CoreWrapper.getMemoryState(MemoryType.Vram);
							_paletteData = CoreWrapper.getMemoryState(MemoryType.PaletteRam);
							_spriteData = CoreWrapper.getMemoryState(MemoryType.SpriteRam);
							sw.Stop();
						}

						this.BeginInvoke((MethodInvoker)(() => {
							double emulatedHz = Stopwatch.Frequency / (double)sw.ElapsedTicks * stepsToRun / 2;
							lblHz.Text = emulatedHz.ToString("0");

							UpdateUI();
						}));
					}

					if(_autoRun) {
						Interlocked.Add(ref _stepsToRun, _refreshSpeed);
					} else {
						System.Threading.Thread.Sleep(50);
					}
				}
			});
		}

		private void UpdateRam()
		{
			lock(_runLock) {
				if(_vramChanged) {
					CoreWrapper.setMemoryState(MemoryType.Vram, ((StaticByteProvider)hexVram.ByteProvider).Bytes.ToArray());
				}
				if(_paletteRamChanged) {
					CoreWrapper.setMemoryState(MemoryType.PaletteRam, ((StaticByteProvider)hexPaletteRam.ByteProvider).Bytes.ToArray());
				}
				if(_spriteRamChanged) {
					CoreWrapper.setMemoryState(MemoryType.SpriteRam, ((StaticByteProvider)hexSpriteRam.ByteProvider).Bytes.ToArray());
				}
			}
			_vramChanged = false;
			_paletteRamChanged = false;
			_spriteRamChanged = false;
		}

		private void UpdateUI()
		{
			lblHalfCycle.Text = _previousState.halfcycle.ToString();
			lblPixel.Text = _previousState.hpos.ToString();
			lblScanline.Text = _previousState.vpos.ToString();

			lblClk.Text = _previousState.clk.ToString();
			lblAb.Text = _previousState.ab.ToString("X4");
			lblD.Text = _previousState.d.ToString("X2");

			UpdateMemoryViews();
			UpdateLogList();
		}

		private void UpdateMemoryViews()
		{
			StaticByteProvider vramBp = new StaticByteProvider(_vramData);
			StaticByteProvider paletteBp = new StaticByteProvider(_paletteData);
			StaticByteProvider spriteBp = new StaticByteProvider(_spriteData);
			hexVram.ByteProvider = vramBp;
			hexPaletteRam.ByteProvider = paletteBp;
			hexSpriteRam.ByteProvider = spriteBp;
			vramBp.ByteChanged += (index, e) => { _vramChanged = true; };
			paletteBp.ByteChanged += (index, e) => {
				//Mirror palette writes
				int i = (int)index;
				if(i == 0x10 || i == 0x14 || i == 0x18 || i == 0x1C) {
					paletteBp.WriteByte(i - 0x10, paletteBp.Bytes[i]);
				} else if(i == 0x00 || i == 0x04 || i == 0x08 || i == 0x0C) {
					paletteBp.WriteByte(i + 0x10, paletteBp.Bytes[i]);
				}
				_paletteRamChanged = true;
			};
			spriteBp.ByteChanged += (index, e) => { _spriteRamChanged = true; };
		}

		private void UpdateLogList()
		{
			lstLogView.BeginUpdate();

			if(_needColumnUpdate) {
				_needColumnUpdate = false;
				lstLogView.Clear();
				foreach(string column in _tracedColumns) {
					lstLogView.Columns.Add(column);
				}

				for(int i = 0; i < 100; i++) {
					ListViewItem item = new ListViewItem("");
					for(int j = 0; j < _tracedColumns.Count - 1; j++) {
						item.SubItems.Add("");
					}
					lstLogView.Items.Add(item);
				}
			}

			int pos = 0;
			int row = 0;
			bool endOfArray = false;
			while(row < 100) {
				for(int j = 0; j < _tracedColumns.Count; j++) {
					if(_previousState.recentLog[pos] == -1) {
						endOfArray = true;
					}
					string newVal = (pos >= _previousState.recentLog.Length || endOfArray) ? "" : _previousState.recentLog[pos].ToString(chkShowInHex.Checked ? "X2" : "");
					if(lstLogView.Items[row].SubItems[j].Text != newVal) {
						lstLogView.Items[row].SubItems[j].Text = newVal;
					}
					pos++;
				}

				row++;
			}

			lstLogView.EndUpdate();
		}

		private void Stop()
		{
			btnRun.Text = "Run";
			_autoRun = false;
		}

		private void Step(UInt32 step)
		{
			Interlocked.Exchange(ref _stepsToRun, (int)step);
		}

		private void Reset(string state)
		{
			lock(_runLock) {
				CoreWrapper.reset(state);
				Step(1);
			}
		}

		private void btnRun_Click(object sender, EventArgs e)
		{
			if(_autoRun) {
				btnRun.Text = "Run";
				_autoRun = false;
			} else {
				btnRun.Text = "Stop";
				_autoRun = true;
			}
		}
		
		private void btnStep_Click(object sender, EventArgs e)
		{
			Stop();
			Step(1);
		}

		private void btnNextPixel_Click(object sender, EventArgs e)
		{
			Stop();
			Step(8);
		}

		private void btnNextScanline_Click(object sender, EventArgs e)
		{
			Stop();
			Step(2728);
		}

		private void btnNextFrame_Click(object sender, EventArgs e)
		{
			Stop();
			Step(714736);
		}

		private void btnReset_Click(object sender, EventArgs e)
		{
			if(radResetPowerOn.Checked) Reset("");
			else if(radResetPrerenderOdd.Checked) Reset(_resetStates[0]);
			else if(radResetPrerenderEven.Checked) Reset(_resetStates[1]);
			else if(radResetPostrenderOdd.Checked) Reset(_resetStates[2]);
		}

		private void SaveFile(string filter, Action<string> callback)
		{
			using(SaveFileDialog sfd = new SaveFileDialog()) {
				sfd.InitialDirectory = _dumpPath;
				sfd.Filter = filter;
				sfd.FileName = "data";
				if(sfd.ShowDialog() == DialogResult.OK) {
					callback(sfd.FileName);
				}
			}
		}

		private void LoadFile(string filter, Action<string> callback)
		{
			using(OpenFileDialog ofd = new OpenFileDialog()) {
				ofd.InitialDirectory = _dumpPath;
				ofd.Filter = filter;
				ofd.FileName = "data";
				if(ofd.ShowDialog() == DialogResult.OK) {
					callback(ofd.FileName);
				}
			}
		}

		private void btnSaveState_Click(object sender, EventArgs e)
		{
			SaveFile("Save states (*.ss)|*.ss", (file) => {
				lock(_runLock) {
					UpdateRam();
					File.WriteAllBytes(file, CoreWrapper.getMemoryState(MemoryType.FullState));
				}
			});
		}

		private void btnLoadState_Click(object sender, EventArgs e)
		{
			LoadFile("Save states (*.ss)|*.ss", (file) => {
				lock(_runLock) {
					CoreWrapper.setMemoryState(MemoryType.FullState, File.ReadAllBytes(file));
					_vramChanged = false;
					_paletteRamChanged = false;
					_spriteRamChanged = false;
					Step(1);
				}
			});
		}

		private void btnStartLogging_Click(object sender, EventArgs e)
		{
			if(_logging) {
				btnStartLogging.Text = "Start Logging";
				_logging = false;
				chkLogHex.Enabled = true;
				chkLogCsv.Enabled = true;
				lock(_runLock) {
					CoreWrapper.stopLogging();
				}
			} else {
				using(SaveFileDialog sfd = new SaveFileDialog()) {
					sfd.Filter = "Log file (*.txt)|*.txt";
					sfd.FileName = "tracelog.txt";
					if(sfd.ShowDialog() == DialogResult.OK) {
						lock(_runLock) {
							if(CoreWrapper.startLogging(sfd.FileName, chkLogHex.Checked, chkLogCsv.Checked)) {
								btnStartLogging.Text = "Stop Logging";
								_logging = true;
								chkLogHex.Enabled = false;
								chkLogCsv.Enabled = false;
							} else {
								MessageBox.Show("Couldn't open file");
							}
						}
					}
				}
			}
		}

		private void btnSelectColumns_Click(object sender, EventArgs e)
		{
			using(frmSelectColumns frm = new frmSelectColumns(_tracedColumns)) {
				if(frm.ShowDialog() == DialogResult.OK) {
					lock(_runLock) {
						_tracedColumns.Clear();
						_tracedColumns.AddRange(frmSelectColumns.SelectedColumns);
						CoreWrapper.setTrace(string.Join("|", _tracedColumns));
						_needColumnUpdate = true;
						Step(1);
					}
				}
			}
		}

		private void cboRefreshSpeed_SelectedIndexChanged(object sender, EventArgs e)
		{
			_refreshSpeed = 4000 / (cboRefreshSpeed.SelectedIndex + 1);
		}

		private void chkShowInHex_CheckedChanged(object sender, EventArgs e)
		{
			UpdateLogList();
		}

		private void btnResetPalette_Click(object sender, EventArgs e)
		{
			SetMemoryState(MemoryType.PaletteRam, new byte[0x20]);
		}

		private void btnImportPalette_Click(object sender, EventArgs e)
		{
			LoadFile("Palette ram (*.pr)|*.pr", (file) => {
				SetMemoryState(MemoryType.PaletteRam, File.ReadAllBytes(file));
			});
		}

		private void btnExportPalette_Click(object sender, EventArgs e)
		{
			SaveFile("Palette ram (*.pr)|*.pr", (file) => {
				lock(this._runLock) {
					UpdateRam();
					File.WriteAllBytes(file, CoreWrapper.getMemoryState(MemoryType.PaletteRam));
				}
			});
		}

		private void btnResetSprite_Click(object sender, EventArgs e)
		{
			SetMemoryState(MemoryType.SpriteRam, new byte[0x100]);
		}

		private void btnImportSprite_Click(object sender, EventArgs e)
		{
			LoadFile("Sprite ram (*.sr)|*.sr", (file) => {
				SetMemoryState(MemoryType.SpriteRam, File.ReadAllBytes(file));
			});
		}

		private void btnExportSprite_Click(object sender, EventArgs e)
		{
			SaveFile("Sprite ram (*.sr)|*.sr", (file) => {
				lock(_runLock) {
					UpdateRam();
					File.WriteAllBytes(file, CoreWrapper.getMemoryState(MemoryType.SpriteRam));
				}
			});
		}

		private void btnResetVram_Click(object sender, EventArgs e)
		{
			SetMemoryState(MemoryType.Vram, new byte[0x3000]);
		}

		private void btnImportVram_Click(object sender, EventArgs e)
		{
			LoadFile("VRAM (*.vr)|*.vr", (file) => {
				SetMemoryState(MemoryType.Vram, File.ReadAllBytes(file));
			});
		}

		private void btnExportVram_Click(object sender, EventArgs e)
		{
			SaveFile("VRAM (*.vr)|*.vr", (file) => {
				lock(_runLock) {
					UpdateRam();
					File.WriteAllBytes(file, CoreWrapper.getMemoryState(MemoryType.Vram));
				}
			});
		}

		public void SetMemoryState(MemoryType type, byte[] data)
		{
			lock(_runLock) {
				UpdateRam();
				CoreWrapper.setMemoryState(type, data);
				_vramData = CoreWrapper.getMemoryState(MemoryType.Vram);
				_paletteData = CoreWrapper.getMemoryState(MemoryType.PaletteRam);
				_spriteData = CoreWrapper.getMemoryState(MemoryType.SpriteRam);
			}
			UpdateMemoryViews();
		}
	}
}
